### ISSUE TITLE
Cannot set theme

### ISSUE THREAD

**Issue by michael-38** [react-monaco-editor/react-monaco-editor#100]
When I try to set the theme of the editor but I'm getting the following error from my browser's console: `context.monaco.editor.setTheme is not a function` (editor.js:214).

Has anyone encountered this before?

     render() {
        const requireConfig = {
          url:
            "https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.1/require.min.js",
          paths: {
            vs: "https://cdnjs.cloudflare.com/ajax/libs/monaco-editor/0.6.1/min/vs"
          }
        };
        return (
          <div className="code-editor">
            <MonacoEditor
              ref="monaco"
              width="1100"
              height="550"
              language="javascript"
              value={this.state.message.code}
              onChange={this.onChange}
              requireConfig={requireConfig}
              theme="vs-black"
        />
      </div>
    );
  }

**Comment by domoritz** [comment]
I haven't seen that before but it would be awesome if you could look into it.

**Comment by blaskovicz** [comment]
@michael-38 you need to upgrade to newer monaco-editor in your require config - say `0.11.1`, perhaps.

`monaco.editor.setTheme()` was added in `0.9.0`:
https://github.com/Microsoft/monaco-editor/blob/171f24402b6ff29c8f346789b780e25f35ac1c4c/CHANGELOG.md#090-03072017

**Comment by domoritz** [comment]
I added a demo
