### ISSUE TITLE
requireConfig 'vs' path is empty

### ISSUE THREAD

**Issue by haldenl** [react-monaco-editor/react-monaco-editor#115]
Hello! I am attempting to use this editor without wading into webpack configs. However, the suggested alternative is not working for me. It looks like the 'vs' path is not valid anymore?

```    
const requireConfig = {
      url: 'https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.1/require.min.js',
      paths: {
        'vs': 'https://www.mycdn.com/monaco-editor/0.6.1/min/vs'
}
```

**Comment by domoritz** [comment]
I don't know what `https://www.mycdn.com/` is. Maybe you can use something like `https://cdn.jsdelivr.net/npm/monaco@latest/build/vs/`.
