### ISSUE TITLE
Error: Cannot find module "vs/language/typescript/tsWorker"

### ISSUE THREAD

**Issue by lolzcalvin** [react-monaco-editor/react-monaco-editor#134]
I got this error while using react-monaco-editor with Electron, turns out even the example provided in the repo has the same error as well.
Full error:
```
Uncaught Error: Cannot find module "vs/language/typescript/tsWorker".

Error: Cannot find module "vs/language/typescript/tsWorker".
    at webpackEmptyContext (:8886/0.index.js:11)
    at index.js:75011
    at webpackEmptyContext (:8886/0.index.js:11)
    at index.js:75011
    at index.js:16882
```
at the same time, via the "another editor" within the example, another error occurs too:
```
Uncaught Error: Cannot find module "vs/language/json/jsonWorker".

Error: Cannot find module "vs/language/json/jsonWorker".
    at webpackEmptyContext (:8886/0.index.js:11)
    at index.js:75011
    at webpackEmptyContext (:8886/0.index.js:11)
    at index.js:75011
    at index.js:16882
```

I do not have any idea what causes these errors, but it seems like it fails to locate the workers properly, and they're language specific (first editor uses javascript, therefore tsWorker should be located, while the second editor uses json). They could be the culprits that auto-completion pop-up isn't working properly.

**Comment by oferitz** [comment]
Having the exact same problem also Electron.

**Comment by lolzcalvin** [comment]
`monaco-editor-webpack-plugin` does not work in my webpack-dev-server, it's either giving me `Not rewriting GET /dist/renderer.dev.js because the path includes a dot (.) character.` or just plain `Rewriting GET /dist/renderer.dev.js to /index.html` after disabling dot rule. It basically says that the server can't locate index.html for some reasons, and for some reasons, removing monaco webpack plugin will work, though with the errors concerned in this issue.

the webpack config is provided here.[https://gist.github.com/lolzcalvin/e80f3decd1d22defeb7d64c17367b7da](url)

**Comment by domoritz** [comment]
Since this is a webpack issue, I am going to close it.

**Comment by zerocewl** [comment]
> `monaco-editor-webpack-plugin` does not work in my webpack-dev-server, it's either giving me `Not rewriting GET /dist/renderer.dev.js because the path includes a dot (.) character.` or just plain `Rewriting GET /dist/renderer.dev.js to /index.html` after disabling dot rule. It basically says that the server can't locate index.html for some reasons, and for some reasons, removing monaco webpack plugin will work, though with the errors concerned in this issue.
> 
> my webpack config is provided [here.](https://gist.github.com/lolzcalvin/e80f3decd1d22defeb7d64c17367b7da)

Thx for sharing your webpack config example!
