### ISSUE TITLE
Custom Language sample

### ISSUE THREAD

**Issue by pointnet** [react-monaco-editor/react-monaco-editor#136]
I'm trying to use our own custom language with react-monaco-editor but can't find a way to achieve it.

Does someone have a sample using a custom language ?

I'm trying to get this part ported to react-monaco-editor:
```
<script>
	var require = {
		paths: {
			'vs/language/athena': 'http://localhost:8080/release/dev',
			'vs': '../node_modules/monaco-editor-core/dev/vs'
		}
	};
</script>
<script src="../node_modules/monaco-editor-core/dev/vs/loader.js"></script>
<script src="../node_modules/monaco-editor-core/dev/vs/editor/editor.main.nls.js"></script>
<script src="../node_modules/monaco-editor-core/dev/vs/editor/editor.main.js"></script>
<script>
	require([
		'vs/language/athena/src/monaco.contribution'
	], function() {
	        monaco.languages.register({
        	    id: 'athena',
	            extensions: ['.athena'],
        	});
	});
</script>
```

**Comment by tatomyr** [comment]
Maybe this will help you:
[new language settings](https://github.com/tatomyr/estimate-it/blob/master/src/components/Estimate/editor-config.js) and [how the language is registered in MonacoEditor](https://github.com/tatomyr/estimate-it/blob/master/src/components/Estimate/Editor.js)

**Comment by domoritz** [comment]
I used it in https://github.com/uwdata/draco-editor/blob/master/src/draco-editor/components/Editor.tsx. Does that help?

**Comment by pointnet** [comment]
It does not help, I need to "require" my language because it's a complex one, as typescript, we've got a webworker with a parser and so on.

For now, I'm including my language in monaco-editor sources and build it myself so it's included by design in the monaco bundle but that's an ugly trick :(

**Comment by peidongGuo** [comment]
@pointnet   Do you find the solution?

**Comment by tteguayco** [comment]
> Maybe this will help you: [new language settings](https://github.com/tatomyr/estimate-it/blob/master/src/components/Estimate/editor-config.js) and [how the language is registered in MonacoEditor](https://github.com/tatomyr/estimate-it/blob/master/src/components/Estimate/Editor.js)

Wow, thanks a lot for those resources @tatomyr! They helped me after many failed attempts trying to add my own custom language!

**Comment by beganovich** [comment]
For anyone coming at this in 2024:

```tsx
import Editor from '@monaco-editor/react';

<Editor 
     beforeMount={(monaco) => monaco.languages.register()}
/>
```
