### ISSUE TITLE
Calling setModalLanguage break the theme setting

### ISSUE THREAD

**Issue by alaibe** [react-monaco-editor/react-monaco-editor#149]
Hi there,

When I call:
```
  this.state.monaco.editor.setModelLanguage(this.state.editor.getModel(), 'json');
```
with a component definition like that:

```
<MonacoEditor
  width="800"
  height="600"
  theme="vs-dark"
  value={this.props.file.content}
  onChange={this.props.onFileContentChange}
  editorDidMount={(editor, monaco) => this.editorDidMount(editor, monaco)}
/>
```

Then the theme always revert to 'vs' but the minimap stays dark.
It only happens with the `json` language.

I am using the version: 0.14.3 of Monaco editor

Do you have any idea of what's happening?

**Comment by domoritz** [comment]
That's odd. Could you look into this and send a PR to fix it? I don't have the cycles to look into this anytime soon.

**Comment by domoritz** [comment]
That sounds like a monaco issue not related to this library.
