### ISSUE TITLE
Cross Domain - requireConfig not working

### ISSUE THREAD

**Issue by nperryEG** [react-monaco-editor/react-monaco-editor#154]
In my setup I have two different domains "example-site.com" and "code-editor.com". The code-editor.com contains a react app (based on CRA) that utilizes react-monaco-editor, the goal of this app is put a code editor on the targets site (in this scenario example-site.com). This is done via a script that is included on example-site.com which includes the code-editor.com bundle and executes it on the page, however I believe I have run into the problem described [here](https://github.com/Microsoft/monaco-editor/blob/master/docs/integrate-amd-cross.md). 

Looking at the repo's example I attempted to follow that of the AnotherEditor Component as demonstrated below which I believe corresponds to the monaco-editor's intregation process for cross domain setups. However it appears that the requireConfig is no longer a prop on the [component](https://github.com/superRaytin/react-monaco-editor/blob/master/src/editor.js).
Is there a different approach around implementing this?

Example
``` 
 <MonacoEditor
    // ref="monaco"
    language={this.props.language}
    ref={this.props.editorRef}
    height={this.props.height}
    width={this.props.width}
    theme="vs-dark"
    value={this.props.code}
    options={{ scrollBeyondLastLine: false, ...this.props.options }}
    onChange={this.props.onChange}
    requireConfig={{
        url: 'https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.1/require.min.js',
        paths: {
            vs: ' https://unpkg.com/monaco-editor@0.14.3/min/vs'
        }
    }}
    editorDidMount={this.props.editorDidMount}
/>
```

**Comment by domoritz** [comment]
`requireConfig` doesn't exist anymore.
