### ISSUE TITLE
Require Config for browser localized language

### ISSUE THREAD

**Issue by tom-s** [react-monaco-editor/react-monaco-editor#155]
Hi. I'm trying to set a language for monaco editor as shown in their example:https://github.com/Microsoft/monaco-editor-samples/blob/master/browser-amd-localized/index.html

There doesn't seem to be a requireConfig prop anymore, how could i set the language ?
I believe this is a related to https://github.com/superRaytin/react-monaco-editor/issues/154

Many thanks !

**Comment by domoritz** [comment]
`requireConfig` doesn't exist anymore.
