### ISSUE TITLE
Error compiling

### ISSUE THREAD

**Issue by colombod** [react-monaco-editor/react-monaco-editor#171]
with the following dependencies:
"react-monaco-editor": "0.21.0", (same with 0.22.0)
 "monaco-editor": "0.15.1",
"monaco-editor-webpack-plugin": "1.7.0",

 I get this errors

Error in ./node_modules/react-monaco-editor/lib/editor.js

  Module not found: 'monaco-editor/esm/vs/editor/editor.api' in 'abc\node_modules\react-monaco-editor\lib'

Error in ./node_modules/react-monaco-editor/lib/diff.js

  Module not found: 'monaco-editor/esm/vs/editor/editor.api' in 'abc\node_modules\react-monaco-editor\lib'

my previous dependencies were:
"react-monaco-editor": "0.18.0",
 "monaco-editor": "0.14.3",
"monaco-editor-webpack-plugin": "1.5.1",

**Comment by domoritz** [comment]
Can you try the example in this repo?

**Comment by colombod** [comment]
when I follow the instruction and run the example I notice that the version of react-monaco-editor installed via yarn is 

  "name": "react-monaco-editor",
  "version": "0.14.1",

is this correct (is the content of node_modules inside the example folder)
