### ISSUE TITLE
automaticLayout and height 100%?

### ISSUE THREAD

**Issue by stoplion** [react-monaco-editor/react-monaco-editor#175]
https://codesandbox.io/s/2ow651l5mp

How is it possible to get a height 100% with automaticLayout and height 100%?

**Comment by lyckligtax** [comment]
Have a look at the sandbox I forked from your example https://codesandbox.io/s/549woqwkyl
You can set the appropriate styles of surrounding Containers to the desired dimensions:

`html,
body,
#root {
  height: 100%;
  width: 100%;
  padding: 0;
  margin: 0;
}`

and import the css-rules:

`import "./styles.css";`
