### ISSUE TITLE
Controlled version of component?

### ISSUE THREAD

**Issue by PullJosh** [react-monaco-editor/react-monaco-editor#194]
This is a big request, but I thought I'd ask in case it can be done.

Right now, `react-monaco-editor` is an uncontrolled component. In props, you can pass a default value, but after that, things are out of your hands. You can read the value of the editor `onChange`, but as far as I can tell, you can't set the value again later (easily).

I want to create an app in which it is possible to "record" the history of the state of the editor, and play it back later. (Similarly to how it's done in the Redux devtools, if you've ever used those.)

To do this, I need complete control of the monaco editor. The entire state, including the editor's content and selections, needs to belong to the parent component.

Is this possible? If so, how would I go about making it happen?

**Comment by PullJosh** [comment]
For reference, [`react-codemirror2`](https://www.npmjs.com/package/react-codemirror2) has [something similar](https://www.npmjs.com/package/react-codemirror2#controlled-usage) to what I'm looking for. Unfortunately, the controlled codemirror component only allows controlling the editor value, not the selections and other state:

```js
import {Controlled as CodeMirror} from 'react-codemirror2'
 
<CodeMirror
  value={this.state.value}
  onBeforeChange={(editor, data, value) => {
    this.setState({value});
  }}
/>
```

Ideally, I'd like to control *everything*. And, of course, I'd like the monaco editor in place of codemirror.

**Comment by domoritz** [comment]
You can access the editor instance that we create, no?

**Comment by PullJosh** [comment]
Looks like you're right! I should have done a little more investigating myself before asking, it seems.

Here's a controlled component I made (which allows passing both the value *and* selections of the editor), in case anyone in the future has the same need:
https://codesandbox.io/s/883y2zmp6l
