### ISSUE TITLE
Uncaught TypeError: Cannot read property 'jsonDefaults' of undefined

### ISSUE THREAD

**Issue by xihaoxiaohao** [react-monaco-editor/react-monaco-editor#197]
When I use npm to install and start the app, it failed with the error `jsonDefaults of undefined`.

Is there a way using npm instead of yarn?

**Comment by domoritz** [comment]
The issue seems to be some newer version of something. Can you help debug?

**Comment by ftcvlad** [comment]
I was having the same issue after updating react-monaco-editor. 

The issue resolved when started to use `MonacoWebpackPlugin` instead of deprecated `requireConfig`
