### ISSUE TITLE
react-monaco-editor + gatsby

### ISSUE THREAD

**Issue by JeffWScott** [react-monaco-editor/react-monaco-editor#204]
This guy was able to get monaco-editor to work with Gatsby is there a way to take this approach and get this to work with react-monaco-editor?  The webpack-plugin config approach you specify in your readme doesn't work with Gatsby.

https://medium.com/@michaellperry/gatsby-pages-with-client-only-script-85a7c5664a27#--respond

**Comment by sgrove** [comment]
@JeffWScott Did you ever figure this out? I have a working dev environment, but hitting a snag in gatsby build

**Comment by JeffWScott** [comment]
@sgrove this was my solution.

https://github.com/Lamden/ide/blob/master/src/components/monacoeditor.jsx
