### ISSUE TITLE
Can't undo when value is changed externally

### ISSUE THREAD

**Issue by sorawee** [react-monaco-editor/react-monaco-editor#211]
Consider the following:

```javascript
import React, {useState} from 'react';
import MonacoEditor from 'react-monaco-editor';

const App = () => {
  const [code, setCode] = useState('// type your code');
  const handleChange = newVal => setCode(newVal);
  const handleClick = () => setCode('abcdef');
  return (
    <>
      <button onClick={handleClick}>click me</button>
      <MonacoEditor
        width="800"
        height="600"
        language="javascript"
        value={code}
        onChange={handleChange}
      />
    </>
  );
}

export default App;
```

We can edit code in the editor normally, and can perform the undo operation. When we click "click me", the code also changes as it should. However, this seems to also reset the undo stack, as we can't undo to the previous state before "click me" is clicked.

This seems to relate to #9, but I'm not 100% sure.

**Comment by domoritz** [comment]
Conflicts with https://github.com/react-monaco-editor/react-monaco-editor/issues/215

**Comment by siddhant1** [comment]
Will have a look if I get time!  Open for anyone to pick up

**Comment by domoritz** [comment]
Fixed in master
