### ISSUE TITLE
Point Travis CI to react-monaco-editor/react-monaco-editor

### ISSUE THREAD

**Issue by sorawee** [react-monaco-editor/react-monaco-editor#213]
Travis CI is still pointing to `superRaytin/react-monaco-editor`. This apparently makes the Travis CI integration broken since 6e8135fdabaf37dbbaaf3f0d1c11e2bc2166a5c3.

**Comment by domoritz** [comment]
@superRaytin can you make me an owner of the org so that I can set up Travis?

**Comment by superRaytin** [comment]
@domoritz Done!

**Comment by domoritz** [comment]
Fixed
