### ISSUE TITLE
update value will not update monaco-editor content in 0.26.1

### ISSUE THREAD

**Issue by chnldw** [react-monaco-editor/react-monaco-editor#215]
After `state.content` updated, the content of monaco editor is not updated in 0.26.1.
Downgrade to 0.25.1 works well.
`        return <MonacoEditor
            language="text"
            theme={this.context.theme === "dark" ? "vs-dark" : "vs"}
            value={this.state.content}
            options={options}
        />;
`

**Comment by domoritz** [comment]
@sorawee could this be related to https://github.com/react-monaco-editor/react-monaco-editor/pull/212? If so, we probably need oto revert it.

**Comment by sorawee** [comment]
@chnldw 
- What does "the content of monaco editor is not updated" mean? Could you give more details?
- How did you update `state.content`? Do you have any `onChange`? And can you give us a minimal code that produces the problem?

Currently, I can't see why #212 can cause the "editor is not updated" problem. I tried the following code:

```
import React, {useState} from 'react';
import MonacoEditor from 'react-monaco-editor';

const App = () => {
  const [code, setCode] = useState('hello world');
  const handleClick = () => {
    setCode(code + 'a');
  };
  return (
    <>
      <button onClick={handleClick}>click me</button>
      <MonacoEditor value={code} width="400" height="200" />
    </>
  );
};

export default App;
```

And it functions as an [uncontrolled component](https://reactjs.org/docs/uncontrolled-components.html) as expected.

**Comment by domoritz** [comment]
I think this is causing a bug in the Vega editor: https://github.com/vega/editor/issues/359

**Comment by domoritz** [comment]
We froze updates to the vega editor until this issue is fixed.

**Comment by domoritz** [comment]
Rolling back to pre-0.26 solved the issue. @sorawee Can you help fix this issue?

**Comment by domoritz** [comment]
Fixed in master
