### ISSUE TITLE
MonacoEditor error - invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined.

### ISSUE THREAD

**Issue by s-tuli** [react-monaco-editor/react-monaco-editor#217]
I am running into an issue related to MonacoEditor. The scenario is that I have 2 packages and MonacoEditor is needed in both. The first package has a dependency on the second package. So, I want to remove 'react-monaco-editor' along with the plugin from the first package. I created a common control based on MonacoEditor from  'react-monaco-editor' in the second package.

Issues:
If I remove the 'react-monaco-editor' from the first package in webpack.config,js and package.json, I run into this Issue:**Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports. Check the render method of `MonacoEditorControl`**.

If I do not remove MonacoEditor from the first package, the issue is that I run into memory heap issue for the first package but locally the controls all load up. (I have 'react-monaco-editor' along with the plugin in both the first package and the second package)
**ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory**

**Comment by domoritz** [comment]
This doesn't seem to be related to this library.

**Comment by AlexandroMtzG** [comment]
I know this is from 5 years ago but I was able to fix it with:
```diff tsx
+ {typeof window !== "undefined" && (
  <Editor ... />
+ )}
```
