### ISSUE TITLE
[bug] Monaco theme 

### ISSUE THREAD

**Issue by lvybriage** [react-monaco-editor/react-monaco-editor#221]
I use monaco editor in my webportal on two places. The one, I use theme "vs-light" to render. And the other one, I use theme "vs-dark" to render. But I find that all of their theme is "vs-dark". It's strange.

Someone can help me to deal with this problem?

**Comment by domoritz** [comment]
That's by design: https://github.com/Microsoft/monaco-editor/issues/338
