### ISSUE TITLE
Auto suggestions only working for JavaScript and not for other languages

### ISSUE THREAD

**Issue by reddybhargava** [react-monaco-editor/react-monaco-editor#222]
I'm using react-monaco-editor in my application. But the autosuggestions only work if the language is set as javascript. Even if I add more languages to the monaco-editor-webpack-plugin in webpack.config.js file, it's still doesn't make a difference.
`new MonacoWebpackPlugin({
      languages: [ 'javascript','cpp','java','python']
    }),`

I also tried the example in this repo, even in that if I add more languages to the webpack plugin and use one of those languages in the monaco editor component, the autosuggest still doesn't show up. But if the language is set as javascript in the monaco editor component, auto suggestions show up.

**Comment by domoritz** [comment]
Hmm, can you try just raw Monaco and see whether you can reproduce the issue?

**Comment by reddybhargava** [comment]
Okay sure, I'll try that out.
@domoritz do you have any references for using just raw Monaco with React, I couldn't find much on the internet.

**Comment by domoritz** [comment]
I'd try without react just to see what might be the problem.

**Comment by reddybhargava** [comment]
So I did try on changing languages on the examples provided in [https://github.com/microsoft/monaco-editor-samples] and no luck, the IntelliSense auto-suggestions work only for a few languages.
According to [https://microsoft.github.io/monaco-editor/] the monaco editor supports IntelliSense only for a  few languages. So it's the same with react-monaco-editor as well, right?

How do I add IntelliSense/Auto suggestions for a few other languages?

**Comment by domoritz** [comment]
Okay, then this is not an issue with the react bindings since we just wrap monaco. Monaco should have support for many languages but I've personally only used js and json.

**Comment by reddybhargava** [comment]
@domoritz Yes, I agree. But how do I add/use IntelliSense/Autosuggestions for other languages like python, c++ and java which are not supported by monaco?

**Comment by domoritz** [comment]
I think you need a language server. See https://github.com/Microsoft/monaco-editor/issues/955 for example.
