### ISSUE TITLE
Module parse failed.

### ISSUE THREAD

**Issue by dreamer01** [react-monaco-editor/react-monaco-editor#227]
ERROR in ./node_modules/react-monaco-editor/src/editor.js 55:12
Module parse failed: Unexpected token (55:12)
You may need an appropriate loader to handle this file type.
|   }
| 
>   assignRef = component => {
|     this.containerElement = component;
|   };
 @ ./node_modules/react-monaco-editor/src/index.js 1:0-36 4:0-53

Using with react-boilerplate

**Comment by domoritz** [comment]
Please follow the example in this repo and see whether you can reproduce this error.
