### ISSUE TITLE
MonacoEditor "uncontrolled mode" not working

### ISSUE THREAD

**Issue by chenxinyanc** [react-monaco-editor/react-monaco-editor#229]
**Describe the bug**
According to the documentation, we have
https://github.com/react-monaco-editor/react-monaco-editor/blob/75674ed18b989e5417a498b5929444a34f4c3c55/src/index.d.ts#L50-L55

However, in the implementation, we have
https://github.com/react-monaco-editor/react-monaco-editor/blob/75674ed18b989e5417a498b5929444a34f4c3c55/src/editor.js#L20-L25

This will cause text to be cleared whenever `MonacoEditor` has prop change if `MonacoEditor.value` is `null`.

**To Reproduce**
```tsx
interface IComponentState {
    language: string;
}

export class MyComponent extends React.PureComponent<{}, IComponentState> {

    private _editorDidMount: EditorDidMount = (editor, monaco) => {
        editor.getModel().onDidChangeContent(e => {
            const firstLine = editor.getModel().getLineContent(1);
            this.setState({ language: firstLine });
        });
    }

    public render() {
        return (<MonacoEditor langauge={this.state.language} defaultValue="test" />);
    }

}
```

**Expected behavior**
I don't think we should compare `this.props.value` with `model.getValue()` anymore if `this.props.value` is `null`. This is what uncontrolled mode means, I suppose.

**Screenshots/Logs**

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge 77.0.235.5 dev
 - Bundler: Webpack

- [x] I will try to send a pull request to fix this issue.

**Comment by domoritz** [comment]
Thank you for filing this issue. I suspect we want to check for `null` only or also `undefined`.

**Comment by chenxinyanc** [comment]
I think comparison like `this.props.value != null` will do.

**Comment by domoritz** [comment]
Agreed.

**Comment by Ehesp** [comment]
Can this be closed?
