### ISSUE TITLE
create-react-app fork for react-monaco-editor

### ISSUE THREAD

**Issue by bitjson** [react-monaco-editor/react-monaco-editor#235]
Thanks for this project! I've been using it in [bitauth-ide](https://github.com/bitauth/bitauth-ide) for a while, and it's been invaluable.

My app uses a very standard [`create-react-app`](https://github.com/facebook/create-react-app) setup, but I had to eject in order to add `MonacoWebpackPlugin` to `webpack.config.js`. I'm now trying to upgrade to the latest version of create-react-app, and I'd really like to de-clutter the app by switching back onto the standard create-react-app using the `--scripts-version` option.

I [forked create-react-app](https://github.com/bitauth/create-react-app-bitauth-ide) and [made the changes](https://github.com/bitauth/create-react-app-bitauth-ide/commit/c48c5f1937cc605b7235d6705b35a98e640e9cae), but I'm having trouble resolving dependency issues. What I'm trying:

```sh
npx create-react-app test-app --scripts-version @bitauth/react-scripts-bitauth-ide
cd test-app/
yarn add react-monaco-editor
yarn start
```

And I'm trying to figure out this error:

```
$ react-scripts start
Failed to compile.

Cannot find module 'monaco-editor/esm/vs/editor/standalone/browser/accessibilityHelp/accessibilityHelp'

error Command failed with exit code 1.
```

The same error as https://github.com/react-monaco-editor/react-monaco-editor/issues/168, but I've tried various combinations of installing `react-monaco-editor`, `monaco-editor-webpack-plugin`, and `monaco-editor` in both the project and the react-scripts fork, and I've not been able to get to a working state yet.

Any idea why module resolution is failing here? Or has anyone had success with a `react-scripts` fork which sets up the required configuration for `react-monaco-editor`?

**Comment by xukaifeng** [comment]
I have the same problem and haven't found a solution yet.

**Comment by guoguo0202** [comment]
has the problem been solved?

**Comment by guoguo0202** [comment]
install dependencies “monaco-editor”

**Comment by danieloi** [comment]
I tried this on codesandbox and it didn't work for a similar reason. 

I tried it locally afterwards locally and it did after I installed the monaco-editor. 

Thanks for the great tool!

**Comment by danieloi** [comment]
syntax highlighting still doesn't work without ejecting though...

**Comment by bitjson** [comment]
Update: managed to get it working. I'll be maintaining [the @bitauth/react-scripts-bitauth-ide fork](https://github.com/bitauth/create-react-app-bitauth-ide) if anyone else is interested.

JS-only:
```sh
npx create-react-app --scripts-version=@bitauth/react-scripts-bitauth-ide my-app
```

Typescript:
```sh
npx create-react-app --typescript --scripts-version=@bitauth/react-scripts-bitauth-ide my-app
```

And you can see an example of it working with a custom theme, language, range markers (underlining errors), hover providers, and autocompletion providers in [bitauth-ide](https://github.com/bitauth/bitauth-ide).
