### ISSUE TITLE
Destroying monaco instance on diff will unmount

### ISSUE THREAD

**Issue by hamzahalhariri** [react-monaco-editor/react-monaco-editor#237]
**Describe the bug**
When you have a Diff editor mounted and you try to unmount it, you get an error: `this.editor.getModel().dispose is not a function`

**To Reproduce**
In example, mount Diff editor and unmount it.

**Expected behavior**
Not throwing the error, unmount normally with destroying monaco instance .

**Screenshots/Logs**
![screenshot](https://i.imgur.com/5rcJVo6.png)

**Environment (please complete the following information):**
 - OS: [e.g. mac]
 - Browser [e.g. chrome]
 - Bundler [e.g. webpack]

- [x] I will try to send a pull request to fix this issue. https://github.com/react-monaco-editor/react-monaco-editor/pull/236

**Comment by hamzahalhariri** [comment]
Hi @domoritz 
First of all i wanna say thanks for your lib, it's pretty nice 👍🏽
i just was wondering if there is any chance to build a new version with the latest fixes 🙃
It would be really nice to have these fixes out so we can use it in our project please

Thanks.
Hamzah.

**Comment by domoritz** [comment]
Already done. 0.30.1 is out.

**Comment by hamzahalhariri** [comment]
Thanks a lot!
But i can't see it in NPM
![screenshoot](https://i.imgur.com/xOxb9kg.png)

**Comment by domoritz** [comment]
Hmm, I'll make it again when I get home.
