### ISSUE TITLE
Upgrading to react-monaco-editor 0.30.0 gives "JSX element type 'MonacoEditor' is not a constructor function for JSX elements" error

### ISSUE THREAD

**Issue by adamhagan** [react-monaco-editor/react-monaco-editor#238]
**Describe the bug**
I have upgraded the package in NPM to 0.30.0 (from 0.18.0) and upgraded monaco-editor-webpack-plugin to 1.7.0 (from 1.5.4).

After the upgrade I get the following compilation error:
```
JSX element type 'MonacoEditor' is not a constructor function for JSX elements.
  Types of property 'render' are incompatible.
    Type '() => ReactNode' is not assignable to type '{ (): false | Element; (): ReactNode; }'.
      Type 'ReactNode' is not assignable to type 'false | Element'.
        Type 'string' is not assignable to type 'false | Element'.
```

And I no longer have access to import * as monaco from 'monaco-editor/esm/vs/editor/editor.api' to get the exposed interface types (e.g. editor.IModelContentChangedEvent).

I tried to upgrade the version in the past but got the same error so stayed on v0.18.0 of react-monaco-editor.

**To Reproduce**
- Upgrade to the above version of packages.
- Create a react component that uses the MonacoEditor component E.g:
```
import MonacoEditor from 'react-monaco-editor';
import * as React from 'react';
import * as monaco from 'monaco-editor/esm/vs/editor/editor.api';
public class MyComponent extends React.Component {

   public render() {
     return (<MonacoEditor
                theme='vs-dark'
                value={value}
                width={'100%'}
                height={'100%'}
                editorDidMount={this.editorDidMount}
                options={{
                    model: model,
                    automaticLayout: true,
                    acceptSuggestionOnEnter: 'smart',
                    autoIndent: true,
                    codeLens: true,
                    minimap: {
                        enabled: true
                        showSlider: 'mouseover',
                    },
                    formatOnPaste: true,
                    formatOnType: true,
                    quickSuggestions: { other: false, comments: false, strings: false },
                    snippetSuggestions: 'none',
                    suggestOnTriggerCharacters: true,
                    suggestSelection: 'recentlyUsedByPrefix',
                    wordBasedSuggestions: false,
                    readOnly: false,
                    lineNumbers:  'on',
                }}
                onChange={this.onChange}
                language={'json'}
                editorWillMount={this.editorWillMount}
            />);
      }

  private onChange(newValue: string, event: monaco.editor.IModelContentChangedEvent) {
      // On Change
  }
}
```
- Build the project with webpack and notice the above error.

**Expected behavior**
I'd expect to still be able to access the interfaces and for the MonacoEditor tohave no compilation errors.

**Screenshots/Logs**
If applicable, add screenshots or logs to help explain your problem.

**Environment (please complete the following information):**
 - OS: MacOS (Mojave, 10.14.6)
- Node 12.8.1 
 - Browser Chrome
 - Bundler webpack

**Comment by domoritz** [comment]
Can you reproduce the error with the example in this repo?

**Comment by adamhagan** [comment]
I can’t replicate the same issue in the example.

**Comment by domoritz** [comment]
Then it's probably not because of a bug in this project. I've used the monaco editor in my own project at https://github.com/vega/editor/blob/master/src/components/input-panel/spec-editor/renderer.tsx in a similar way to yours. Maybe it helps.

**Comment by AnKlim** [comment]
The same error
