### ISSUE TITLE
Example app not working

### ISSUE THREAD

**Issue by DenysVuika** [react-monaco-editor/react-monaco-editor#244]
**Describe the bug**
Example application is not working

**To Reproduce**
```
cd example
yarn
yarn start
```

**Expected behavior**
the app should compile and start

**Screenshots/Logs**
```
Error: Cannot find module 'monaco-editor/esm/vs/editor/standalone/browser/accessibilityHelp/accessibilityHelp'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.resolve (internal/modules/cjs/helpers.js:33:19)
```

**Environment (please complete the following information):**
 - OS: [e.g. Linux]
 - Browser [e.g. Firefox, Safari]
 - Bundler [e.g. webpack]

- [ ] I will try to send a pull request to fix this issue.

**Comment by nguyenmanh1507** [comment]
@DenysVuika I think you need run `npm i monaco-editor`

**Comment by krishnaglick** [comment]
How did you fix this?

**Comment by domoritz** [comment]
Maybe by building the library at the top level.

**Comment by krishnaglick** [comment]
Apparently this doesn't actually cause an issue when run, so I'm ignoring it.
