### ISSUE TITLE
How to localize context menu

### ISSUE THREAD

**Issue by PunKHS** [react-monaco-editor/react-monaco-editor#248]
**Is your feature request related to a problem? Please describe.**
I want to use Russian translation for a context menu. But I don't understand how to implement i18n.
I found an example of pure [monaco-editor](https://github.com/Microsoft/monaco-editor-samples/blob/master/browser-amd-localized/index.html).

**Describe the solution you'd like**
Please, give me an example. How to localize the context menu for react-monaco-editor?

**Comment by domoritz** [comment]
I didn't try it out but I suspect that you can just call this code
```js
require.config({ paths: { 'vs': '../node_modules/monaco-editor/min/vs' }});
	require.config({
		'vs/nls' : {
			availableLanguages: {
				'*': 'de'
			}
		}
	});
```

and it will modify some global state. When the react component initializes the component, it will initialize it with your config. Just make sure you call your config stuff before monaco gets initialized.

**Comment by domoritz** [comment]
Closing as there is no immediate action for this module.

**Comment by chengtie** [comment]
> I didn't try it out but I suspect that you can just call this code
> 
> ```js
> require.config({ paths: { 'vs': '../node_modules/monaco-editor/min/vs' }});
> 	require.config({
> 		'vs/nls' : {
> 			availableLanguages: {
> 				'*': 'de'
> 			}
> 		}
> 	});
> ```
> 
> and it will modify some global state. When the react component initializes the component, it will initialize it with your config. Just make sure you call your config stuff before monaco gets initialized.

Hello, where should we put this code in a project?
