### ISSUE TITLE
bump monaco-editor to version 0.18.1

### ISSUE THREAD

**Issue by Yar-R** [react-monaco-editor/react-monaco-editor#250]
mouse scroll does not work in firefox in version prior to 0.18.0
https://github.com/Microsoft/monaco-editor/issues/1353

update dependencies to have
`"monaco-editor": "^0.18.1",`

**Comment by domoritz** [comment]
We're not depending on a particular version: https://github.com/react-monaco-editor/react-monaco-editor/blob/df965b4370e6c0fa0d703e6b2e65ae3fba49ef12/package.json#L58. You can install whatever you want.
