### ISSUE TITLE
Right Click menu doesn't work,

### ISSUE THREAD

**Issue by hadanin** [react-monaco-editor/react-monaco-editor#251]
I create a project using "create-react-app", using npm and then 

npm install react-monaco-editor
npm install monaco-editor-webpack-plugin@1.7.0

Now, I have no error or warning but right click menu doesn't work.

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

**Comment by domoritz** [comment]
Please try the example in this repo and see whether you can reproduce this error. The right click menu works for me here and in https://github.com/vega/editor.

**Comment by hadanin** [comment]
Thanks Dominic!
But I used create-react -app to create my project, therefore I don't have webpack.config.js 

but I installed "monaco-editor-webpack-plugin" seperately

**Comment by domoritz** [comment]
I'm not sure whether monaco-editor-webpack-plugin works without ejecting create-react-app. However, these issues are unrelated to this project and so I cannot help.
