### ISSUE TITLE
Is it possible to avoid installing monaco-editor-webpack-plugin in dependent libraries and apps?

### ISSUE THREAD

**Issue by marek-baranowski** [react-monaco-editor/react-monaco-editor#252]
**Is your feature request related to a problem? Please describe.**
I'm developing a library that is using `react-monaco-editor` with completely custom language, my webpack config looks like this:
```js
const MonacoWebpackPlugin = require('monaco-editor-webpack-plugin');

module.exports = {
  // (...)
  plugins: [
    new MonacoWebpackPlugin({ languages: [] })
  ]
};
```
My problem is that all the apps that use my library need to include this plugin in their webpack config as well, otherwise autocomplete doesn't work. This seems like an unnecessary step, what is worse my clients are usually not very happy about changing their webpack config with something they are not very familiar with.

**Describe the solution you'd like**
Is there a way to bundle all the necessary monaco files / resources during the build of my library so that no additional monaco-related webpack config is needed by dependent apps / libs?

Best Regards!

**Comment by domoritz** [comment]
Have you looked at the docs for bundling Monaco at https://github.com/microsoft/monaco-editor/blob/master/README.md#documentation?

**Comment by bitjson** [comment]
Just wanted to add a note here about this related issue: https://github.com/react-monaco-editor/react-monaco-editor/issues/235

 I'm maintaining [the @bitauth/react-scripts-bitauth-ide fork](https://github.com/bitauth/create-react-app-bitauth-ide) to support `react-monaco-editor` by default.

JS-only:
```sh
npx create-react-app --scripts-version=@bitauth/react-scripts-bitauth-ide my-app
```

Typescript:
```sh
npx create-react-app --typescript --scripts-version=@bitauth/react-scripts-bitauth-ide my-app
```

And you can see an example of it working with a custom theme, language, range markers (underlining errors), hover providers, and autocompletion providers in [bitauth-ide on GitHub](https://github.com/bitauth/bitauth-ide).

**Comment by domoritz** [comment]
Thanks for the example.
