### ISSUE TITLE
Multiple instances of monaco on the same page

### ISSUE THREAD

**Issue by triblondon** [react-monaco-editor/react-monaco-editor#258]
I have multiple instances of monaco, each showing different code but in the same language, on the same page at the same time.  I'm facing a few issues:

* When you focus an editor and start typing into it, the text may instead appear in a different editor.
* If completion providers are registered in `editorWillMount`, then I get each suggestion duplicated as many times as there are editors on the page.

I tried to fix the second of these by accessing monaco globally outside of the React component class:

```javascript
import * as monaco from 'monaco-editor/esm/vs/editor/editor.api'
monaco.languages.registerCompletionItemProvider('mylanguage', {
  provideCompletionItems: myCompleterFunction
})
```

This does work, but means that completers don't have access to any state or props associated with the instance of the editor that it is providing completions for, which is necessary in my case because each editor is for a different event handler and different variables are available in each one (though they are still fundamentally the same language).

I'm not sure how much of this is a bug and how much is my error, or whether react-monaco simply doesn't support multiple concurrent instances.  Any guidance much appreciated!

**Comment by triblondon** [comment]
Since completers are connected to a language definition, I suspect my only option might be to classify each editor as a different language?

**Comment by domoritz** [comment]
That’s odd. Can you compare to the example on this repo?

**Comment by triblondon** [comment]
OK, so regarding weird interactions between editors I realised that I was not binding my onChange function to the instance.  Idiot.  Sorry.

It's still true though that language definitions cannot be made inside an instance, because they register themselves against the monaco global, so to avoid duplicate completions, it's necessary to register completion providers against the monaco API directly:

```javascript
import * as monaco from 'monaco-editor/esm/vs/editor/editor.api'

monaco.languages.register({ id: 'mylang' })
monaco.languages.setMonarchTokensProvider('mylang', myLanguageSpec)
monaco.languages.setLanguageConfiguration('mylang', { ... })
```

So I can't provide context specific completions unless I define a language for each editor instance, and associate them each using a unique language name.  I think this is just how monaco works, but do tell me if I'm barking up the wrong tree.  Otherwise, feel free to close this issue!

**Comment by domoritz** [comment]
If you think react monaco editor could do something to help with this, feel free to send a pull request. I'm going to close this issue now.
