### ISSUE TITLE
[Documentation] Add instructions on how to use with popular 'create-react-app' 

### ISSUE THREAD

**Issue by masbaehr** [react-monaco-editor/react-monaco-editor#263]
Hey, i spent literally hours to understand how to use the monaco-editor-webpack-plugin with the popular https://github.com/facebook/create-react-app 

This comes with embedded webpack thus the webpack.config.js cannot be modified directly. What can be done is the following: 

install dev dependencies:  copy-webpack-plugin, react-app-rewired
change scripts from "react-scripts *" to "react-app-rewired *" in package.json

add config-overrides.js to the root folder with following content

```javascript
const MonacoWebpackPlugin = require('monaco-editor-webpack-plugin');

module.exports = function override(config, env) {
  config.plugins.push(new MonacoWebpackPlugin({
    languages: ['json']
  }));
  return config;
}
 
```
It would probably help a lot of 'newbies' to get it up and running, so it might be useful adding this to the readme

**Comment by domoritz** [comment]
I totally agree. Can you send a pull request? Thanks!
