### ISSUE TITLE
How to implement tabs in monaco-react

### ISSUE THREAD

**Issue by Ezak91** [react-monaco-editor/react-monaco-editor#269]
Hey,

in the js monaco this seems to be state of the art:

> To implement tabs, the recommended way is:
> 
> 	create a single editor instance via monaco.editor.create({ ... , model: null })
> 	create N model instances via monaco.editor.createModel(...).
> 	switch tabs by calling editorInstance.setModel(modelInstance)
> 	for each model, you can save its view state (cursor, scroll position, etc) via editorInstance.saveViewState() and restore it via editorInstance.restoreViewState().

but how was it with monaco-react? If we create a new Component for each tab, we get errors because we using same variable name in different tabs

Thank you very much

**Comment by domoritz** [comment]
You can have the tabs separately from the editor component. Check out Vega/editor where I added tabs.
