### ISSUE TITLE
Cannot find module 'monaco-editor/esm/vs/editor/editor.worker' with react-monaco-editor

### ISSUE THREAD

**Issue by Jasmin2895** [react-monaco-editor/react-monaco-editor#272]
I am using react-monaco-editor in my current project and facing some issue while setting it up.
```shell
Cannot find module 'monaco-editor/esm/vs/editor/editor.worker'

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! chatbot_compiler@0.1.0 start: `react-app-rewired start`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the chatbot_compiler@0.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above
```

I have made the following changes in my package changes and config-overrides.js. 
```json
"scripts": {
    "start": "react-app-rewired start",
    "build": "react-app-rewired build",
    "test": "react-app-rewired test",
    "eject": "react-app-rewired eject",
    "lint:fix": "eslint src/**/*.js --fix"
  },
```
```javascript
const MonacoWebpackPlugin = require("monaco-editor-webpack-plugin");

module.exports = function override(config, env) {
  config.resolve = {
    alias: {
      "monaco-editor": "monaco-editor/esm/vs/editor/editor.api.js"
    }
  };
  config.plugins.push(
    new MonacoWebpackPlugin({
      languages: ["json"]
    })
  );
  return config;
};

```
Any help would be highly appreciated. Thanks in advance 😅

**Comment by domoritz** [comment]
Is the alias needed? Does the example in this repo work for you?

**Comment by Ehesp** [comment]
Have you got the `monaco-editor` dependency added?

**Comment by buckleader** [comment]
I have added `react-monaco-editor`, not `monaco-editor` separately.

**Comment by buckleader** [comment]
@domoritz I was searching for a solution and then I came across this https://github.com/microsoft/monaco-editor-webpack-plugin/issues/43#issuecomment-436479402

No luck without the alias as well 😞

**Comment by Ehesp** [comment]
@Jasmin2895 yeh you need to install `monaco-editor` too, as it uses it under the hood. It's only a peer dependency so won't install with this package.

**Comment by Jasmin2895** [comment]
Yes, it worked thanks! 👍 @Ehesp

**Comment by domoritz** [comment]
I made monaco a dependency in 496c0a8 to prevent this kind of issue in the future.

**Comment by deepansh-maurya** [comment]
thank you........................................................... @Ehesp
