### ISSUE TITLE
folding and formatting

### ISSUE THREAD

**Issue by YumcoderCom** [react-monaco-editor/react-monaco-editor#274]
**Is your feature request related to a problem? Please describe.**
- fold and unfold
![image](https://user-images.githubusercontent.com/29568969/77815837-b5e42d00-70db-11ea-9c5b-4ac96de7e37a.png)

- format json or javascript code
![image](https://user-images.githubusercontent.com/29568969/77815828-99e08b80-70db-11ea-86ba-343bd12882cf.png)

**Describe the solution you'd like**
enable folding and formatting by setting options

**Comment by domoritz** [comment]
You can pass Monaco options. Does it not work?

**Comment by domoritz** [comment]
Actually, it works for me. Try hovering over the left side of the editor to reveal the folding icons.
