### ISSUE TITLE
Intellisense Suggest for Functions in different languages

### ISSUE THREAD

**Issue by icy-meteor** [react-monaco-editor/react-monaco-editor#275]
I would like this feature of having methods as part of some standard library to be displayed while writing the code. I did find a solution for the same using https://github.com/TypeFox/monaco-languageclient but then it requires me to run the IDE on a server. 

Reference: https://github.com/microsoft/monaco-editor/issues/955
It would be great to have it out of the box, in the UI itself without having to run a separate server.
Something like in this image:
![image](https://user-images.githubusercontent.com/22114682/78922275-e0f35700-7ab3-11ea-84fc-d55f6429a032.png)

**Comment by domoritz** [comment]
Did you mean to file this against monaco? I don't think this feature request applies to react monaco.
