### ISSUE TITLE
'MonacoEditor' is not a constructor function for JSX elements

### ISSUE THREAD

**Issue by AnKlim** [react-monaco-editor/react-monaco-editor#276]
Hello. 
I have created react .tsx application, have installed "react-monaco-editor" v.0.36.0, "monaco-editor-webpack-plugin" v.1.9.0 and "monaco-editor" v.0.20.0. 

package.json
`{
  "name": "new",
  "version": "1.0.0",
  "description": "noone",
  "main": "index.js",
  "scripts": {
    "watch-webpack": "webpack --config webpack/webpack.dev.js --watch",
    "watch-gulp": "gulp watch",
    "watch": "concurrently \"npm:watch-*\"",
    "dev": "webpack --config webpack/webpack.dev.js",
    "build": "webpack --config webpack/webpack.prod.js"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@microsoft/sp-core-library": "1.4.1",
    "@microsoft/sp-lodash-subset": "1.4.1",
    "@microsoft/sp-office-ui-fabric-core": "^1.8.2",
    "@microsoft/sp-webpart-base": "1.4.1",
    "@types/react": "^16.8.19",
    "@types/react-dom": "^16.8.4",
    "@uifabric/styling": "^7.0.3",
    "@uifabric/utilities": "^7.0.3",
    "monaco-editor": "^0.20.0",
    "monaco-editor-webpack-plugin": "^1.9.0",
    "office-ui-fabric-react": "^7.5.3",
    "react": "^16.8.6",
    "react-dom": "^16.8.6",
    "react-monaco-editor": "^0.36.0"
  },
  "devDependencies": {
    "@microsoft/loader-load-themed-styles": "^1.7.160",
    "@types/es6-promise": "^3.3.0",
    "@types/webpack-env": "^1.13.9",
    "concurrently": "^4.1.0",
    "css-loader": "^2.1.1",
    "css-modules-typescript-loader": "^2.0.3",
    "fork-ts-checker-webpack-plugin": "^1.3.4",
    "gulp": "^4.0.2",
    "node-sass": "^4.12.0",
    "sass-loader": "^7.1.0",
    "style-loader": "^0.23.1",
    "ts-loader": "^6.0.2",
    "tslint": "^5.17.0",
    "tslint-config-standard": "^8.0.1",
    "typescript": "^3.5.1",
    "webpack": "^4.32.2",
    "webpack-cli": "^3.3.2",
    "webpack-merge": "^4.2.1",
    "webpack-visualizer-plugin": "^0.1.11"
  }
}`

Then I have followed by this instruction https://github.com/react-monaco-editor/react-monaco-editor#using-with-webpack. 
In webpack.config.js I have added MonacoWebpackPlugin.

webpack.config.js
`const path = require('path');
const merge = require('webpack-merge');
const ForkTsCheckerWebpackPlugin = require('fork-ts-checker-webpack-plugin');
const Visualizer = require('webpack-visualizer-plugin');
const MonacoWebpackPlugin = require('monaco-editor-webpack-plugin');

module.exports = merge({
    target: "web",
    entry: {
        'state-machine-diagraming-tool-webpart-bundle': path.join(__dirname, '../src/webparts/stateMachineDiagramingTool/StateMachineDiagramingToolWebPart.ts')
    },
    output: {
        path: path.join(__dirname, '../dist'),
        filename: '[name].js',
        libraryTarget: "umd",
        library: "[name]"
    },
    performance: {
        hints: false
    },
    externals: [
        /^@microsoft\//,
        'StateMachineDiagramingToolWebPartStrings',
        'ControlStrings'],
    module: {
        rules: [
            {
                test: /\.tsx?$/,
                loader: 'ts-loader',
                options: {
                    transpileOnly: true
                },
                exclude: /node_modules/
            },
            {
                test: /\.css$/,
                use: [
                    {
                        loader: "@microsoft/loader-load-themed-styles", // hack, loads ouif themable styles
                        options: {
                            async: true
                        }
                    },
                    {
                        loader: 'css-loader'
                    }
                ]
            },
            {
                test: /\.scss$/,
                use: [
                    {
                        loader: "@microsoft/loader-load-themed-styles", // hack, loads ouif themable styles
                        options: {
                            async: true
                        }
                    },
                    'css-modules-typescript-loader',
                    {
                        loader: 'css-loader',
                        options: {
                            modules: true
                        }
                    }, // translates CSS into CommonJS
                    "sass-loader" // compiles Sass to CSS, using Node Sass by default
                ]
            }
        ]
    },
    resolve: {
        extensions: ['.ts', '.tsx', '.js']
    },
    plugins: [new ForkTsCheckerWebpackPlugin({
        tslint: true
    }),
    new Visualizer(),
    new MonacoWebpackPlugin({
      languages: ["json", "javascript", "typescript"],
    })]
});`

**Describe the bug**
In class App in tag <MonacoEditor> everything was underlined by red line with next error.
`JSX element type 'MonacoEditor' is not a constructor function for JSX elements.
  The types returned by 'render()' are incompatible between these types.
    Type 'ReactNode' is not assignable to type 'false | Element'.
      Type 'string' is not assignable to type 'false | Element'.ts(2605)`

I have tested example from react-monaco-editor repository and it's working.
I expected that my error will not occure 'cos I have done all step, but by some reason it was :(
I understand that it's my fault, cos more part of people did not faced with it, but I really need help, please.
Also I've found the same issue but without any solution https://github.com/react-monaco-editor/react-monaco-editor/issues/238.

**Screenshots/Logs**
![image](https://user-images.githubusercontent.com/35483429/79115457-8e08f080-7d8e-11ea-96e2-0d173e704646.png)

**Environment (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 68
 - Bundler webpack

**Comment by domoritz** [comment]
We moved to typescript. This issue should be fixed now.
