### ISSUE TITLE
Implement onDidChangeContentModel

### ISSUE THREAD

**Issue by Jointos** [react-monaco-editor/react-monaco-editor#277]
The simple onChange triggers when value is changed by code,which restrics controllability of the component. original monace has an even called onDidChangeContentModel, which fires only if user changes the text in editor

**Comment by hemavidal** [comment]
This exxample would help on how to call onDidChangeContentModel:
```javascript
<MonacoEditor
editorDidMount={editor => {
  editor.onDidChangeModelContent(() => {
    const code = editor.getValue()
    this.setState({ code })
  })
}}
```
