### ISSUE TITLE
Could not create web worker(s). Falling back to loading web worker code in main thread, which might cause UI freezes

### ISSUE THREAD

**Issue by llfylwg** [react-monaco-editor/react-monaco-editor#280]
**Describe the bug**
i get the error 'Could not create web worker(s). Falling back to loading web worker code in main thread, which might cause UI freezes'.  
how can i resolve it?

**Comment by llfylwg** [comment]
vendor.819b7f21.js:283647 Error: Unexpected usage
    at EditorSimpleWorkerImpl.push.bbb0070fc8e90df7a79b.BaseEditorSimpleWorker.loadForeign

**Comment by domoritz** [comment]
Sounds like an issue with Monaco. Please file an issue there.
