### ISSUE TITLE
Cannot select when setting to readonly

### ISSUE THREAD

**Issue by YiyuanYin** [react-monaco-editor/react-monaco-editor#281]
**Describe the bug**
When I set the editor to readonly, I cannot select the word in the editor to do things like copy

**To Reproduce**
set the option to readonly

**Expected behavior**
with readonly true, I can still select the code

**Comment by domoritz** [comment]
Is this an issue with Monaco or react Monaco? Please file an issue with Monaco if it’s the latter. Closing for now but I can reopen.
