### ISSUE TITLE
ts setCompilerOptions will trigger Could not find source file

### ISSUE THREAD

**Issue by fred8617** [react-monaco-editor/react-monaco-editor#283]
![image](https://user-images.githubusercontent.com/35049517/81625148-98201c80-942a-11ea-8c50-d77ed2f2ab20.png)
![image](https://user-images.githubusercontent.com/35049517/81625166-a66e3880-942a-11ea-89df-378869c62c78.png)

**Comment by domoritz** [comment]
Please provide full reproduction steps starting with the examples in https://github.com/react-monaco-editor/react-monaco-editor/tree/master/example.
