### ISSUE TITLE
Context prop removed in version 0.15

### ISSUE THREAD

**Issue by yuxinzhu** [react-monaco-editor/react-monaco-editor#285]
**Describe the bug**
Prior to v0.15, there was a `context` prop which enabled the component to be mounted to `window` variables outside of the parent window. This was particularly useful for mounting the library in iframes or shadow DOMs.

For some reason, this was removed in release 0.15 ([this diff](https://github.com/react-monaco-editor/react-monaco-editor/commit/241e3d9c7f685506bbf8aac7ab251c490cc0da2e#diff-806fed3130056adbc98407610072d4cf), but the documentation remains in the README.md.

What is the alternative now that this `prop` is removed?

**To Reproduce**
Latest version (0.36) does not interpret the `context` prop.

**Expected behavior**
The library should implement this prop.

**Comment by domoritz** [comment]
Context is not supported anymore and I removed it from the docs. Please send a pull request with the feature added back if you need it.
