### ISSUE TITLE
Why is the code prompt useless and there is no error message

### ISSUE THREAD

**Issue by LookForwordTomorrow** [react-monaco-editor/react-monaco-editor#287]
**Describe the bug**
A clear and concise description of what the bug is. Describe why this is not an issue with Monaco itself. 

**To Reproduce**
A clear description of the environment that causes this bug. Please test the example in the `example` folder.

**Expected behavior**

**Screenshots/Logs**
If applicable, add screenshots or logs to help explain your problem.

**Environment (please complete the following information):**
 - OS: [e.g. Linux]
 - Browser [e.g. Firefox, Safari]
 - Bundler [e.g. webpack]

- [ ] I will try to send a pull request to fix this issue.

**Comment by domoritz** [comment]
Please follow the template.
