### ISSUE TITLE
type issue on 0.39.0

### ISSUE THREAD

**Issue by justnewbee** [react-monaco-editor/react-monaco-editor#295]
**Describe the bug**

when using 0.39.0, it reports this

「TS2604: JSX element type 'ReactMonacoEditor' does not have any construct or call signatures.」

**To Reproduce**

upgraded from version 0.37.0 to 0.39.0, and the error pops out

**Expected behavior**

works as 0.37.0 did

**Screenshots/Logs**

the message provided above is enough

**Environment (please complete the following information):**

 - OS: Mac
 - Browser: no need
 - Bundler: webpack

- [ ] I will try to send a pull request to fix this issue.

**Comment by fwielstra** [comment]
I'm seeing the same issue; I suspect it has to do with the recent conversion to Typescript (#292), probably the exports aren't all right.

A temporary workaround that seems to be working is to change the import of the editor to: `import MonacoEditor from "react-monaco-editor/lib";`.

**Comment by domoritz** [comment]
Cc @joshuakgoldberg

**Comment by JoshuaKGoldberg** [comment]
D'oh!

https://github.com/react-monaco-editor/react-monaco-editor/blob/94af8886155034c1f20ad82538e6c99e05b4d294/package.json#L7

That should be `lib/index.d.ts`. I'll send a PR.

**Comment by justnewbee** [comment]
great speed! thanks
