### ISSUE TITLE
Syntax Highlighting for JSX

### ISSUE THREAD

**Issue by ChristopherHButler** [react-monaco-editor/react-monaco-editor#300]
**Is your feature request related to a problem? Please describe.**
I would really like to be able to have syntax highlighting for JSX.

**Describe the solution you'd like**
I would like to be able to pass 'jsx' as the language to the MonacoEditor component and get syntax highlighting. 

I apologize if this is already available but I could not find it anywhere in the docs.

**Comment by domoritz** [comment]
This is the repo for the react wrapper for Monica. Please look for help on Monica.
