### ISSUE TITLE
defaultValue is optional but assgined in defaultProps

### ISSUE THREAD

**Issue by diyijing** [react-monaco-editor/react-monaco-editor#302]
**Describe the bug**
A clear and concise description of what the bug is. Describe why this is not an issue with Monaco itself. 
I'd like to use react-monaco-editor with antd Form，but defaultValue causes conflict with a warnning.

**To Reproduce**
A clear description of the environment that causes this bug. Please test the example in the `example` folder.
https://codesandbox.io/s/vigilant-poitras-ru5lw

**Expected behavior**

**Screenshots/Logs**
If applicable, add screenshots or logs to help explain your problem.
Antd will use `children.props.defaultValue === undefined` to judge whether using form is in right way，but  defaultValue in defaultProps is `''`
https://github.com/ant-design/ant-design/blob/53be0fb0a730b0edea4144aaddd4f3a8c4d3f3eb/components/form/FormItem.tsx#L336
![image](https://user-images.githubusercontent.com/18437933/88528366-23c04700-d031-11ea-96c3-d11b106019ae.png)

**Comment by domoritz** [comment]
Is that a problem with antd or Monaco?

**Comment by diyijing** [comment]
> Is that a problem with antd or Monaco?
A compatibility problem between react-monaco-editor ant antd that just cause a warning. Antd expect the children of `From.Item` should be no default value set
I understand adjusting defaultValue maybe a break change for react-monaco-editor

**Comment by domoritz** [comment]
So antd is making some assumption about components. I don't think it's something I am going to fix but I'd be happy to review a pull request with a backwards compatible and clean change.

**Comment by diyijing** [comment]
It's hard to fix this without a break change, I warp MonacoEditor again to avoid this warning 🤣
```typescriptreact
function Editor(props: MonacoEditorProps) {
  return <MonacoEditor {...props} />;
}
```
