### ISSUE TITLE
Editor's Value is preselected when loaded

### ISSUE THREAD

**Issue by glekner** [react-monaco-editor/react-monaco-editor#303]
**Describe the bug**
Editor's Value is preselected when loaded.
The whole content of the Editor is selected when the file is loaded, is there a way to disable this behaviour?

**To Reproduce**
Not sure if its reproduceable in your env, but in my implementation - https://github.com/openshift/console/blob/master/frontend/packages/console-shared/src/components/editor/YAMLEditor.tsx#L46

It happens everytime after upgrading to 0.37.x

**Expected behavior**
The Value of the editor should not be preselected 

**Screenshots/Logs**
![image](https://user-images.githubusercontent.com/24938324/89293423-93a08400-d666-11ea-9ec1-7a053a154bca.png)

**Environment (please complete the following information):**
 - OS: macOS Catalina
 - Browser Chrome 84
 - Bundler Webpack 4

- [ ] I will try to send a pull request to fix this issue.

**Comment by domoritz** [comment]
This looks like a Monaco issue (not react Monaco) or the way it is used.
