### ISSUE TITLE
Reconsider adding Classname prop to Editor component

### ISSUE THREAD

**Issue by hmillison** [react-monaco-editor/react-monaco-editor#319]
Prior discussion: https://github.com/react-monaco-editor/react-monaco-editor/issues/93

It is pretty common in the React ecosystem to expose a prop to allow the consumers of a component to add styles via `className`.

I saw in the previous discussion that it was suggested that you could wrap the Editor in a div, but there are cases where it would be ideal to avoid that.

Would it be possible to add a className prop so I could directly apply styling to the editor. I am happy to open a PR if so.

**Comment by domoritz** [comment]
I'm happy to review a pull request to add class names as a prop. I don't see any reason why we wouldn't do it.
