### ISSUE TITLE
Version 0.41.1 causes webpack to include all monaco features and languages

### ISSUE THREAD

**Issue by steobrien** [react-monaco-editor/react-monaco-editor#322]
This line of the recent commit imports all of Monaco:
https://github.com/react-monaco-editor/react-monaco-editor/commit/8962f33acd672db5c23a3eba508b7be621a293de#diff-a2a171449d862fe29692ce031981047d7ab755ae7f84c707aef80701b3ea0c80R1

As detailed in the readme of https://github.com/microsoft/monaco-editor-webpack-plugin, a different import style should be used to allow tree shaking to work:
```js
import * as monaco from 'monaco-editor/esm/vs/editor/editor.api';
// if shipping only a subset of the features & languages is desired
```

Upgrading from 0.41.0 to 0.41.1 caused our vendored Javascript to increase by 2 MB as a result of this change.

We have worked around by avoiding your default export:
```js
import MonacoEditor from "react-monaco-editor/lib/editor"
```

**Comment by domoritz** [comment]
Ohhh, that's not good. Thanks for the fix. I will update the code .

**Comment by domoritz** [comment]
Thanks for the bug report @steobrien. I fixed the issue and released a patched version.
