### ISSUE TITLE
Text selected when "value" prop changes

### ISSUE THREAD

**Issue by anant-k-singh** [react-monaco-editor/react-monaco-editor#325]
**Describe the bug**
When the value of `value` prop is changed, the delta changes are selected (as shown in attached screenshot). 
_* I am not sure if this is a bug or feature_

**To Reproduce**
1. Type the text "// Some previous code" in editor
2. Get this content value with `onChange` prop and store in a variable
3. Append text "// Code added with "value" prop" to that variable
4. Provide this variable to `value` prop
5. The delta text "// Code added with "value" prop" is selected (as shown in attached screenshot)
6. If the user continues typing, this selected text gets replaced

**Expected behavior**
The text shouldn't be selected, or there should be some way to add text without it getting selected

**Screenshots/Logs**
![image](https://user-images.githubusercontent.com/22440924/104105786-aafb3180-52d6-11eb-900e-8134d0b2bc24.png)

`// Code added with "value" prop` was added/appended to the value of `value` prop of "MonacoEditor" component.

**Environment (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Bundler: webpack

- [X] I will try to send a pull request to fix this issue.

**Comment by anant-k-singh** [comment]
@domoritz Can you please help me understand how to resolve this

**Comment by domoritz** [comment]
I think we just use monaco's `pushEditOperations` in https://github.com/react-monaco-editor/react-monaco-editor/blob/85af6495c952c3d700fab7dbd0c0ecc579a3bb0a/src/editor.tsx#L64. You can look at the behavior to see whether it's expected or whether we should call a different API.

**Comment by anant-k-singh** [comment]
Text getting selected is an expected behaviour when editor's content is updated using `model.pushEditOperations` API.
As per this issue: microsoft/monaco-editor#1811,
We can use the `editor.setValue(newValue)` API to add just update text content (without it getting selected).

**Comment by domoritz** [comment]
according to https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.itextmodel.html#pusheditoperations, only pushEditOperations preserves the undo stack

**Comment by domoritz** [comment]
Won't fix as discussed in https://github.com/react-monaco-editor/react-monaco-editor/pull/327
