### ISSUE TITLE
【Bug Report】display of lineNumbers overlapped when line number is more than 10000

### ISSUE THREAD

**Issue by Indomi** [react-monaco-editor/react-monaco-editor#328]
**Describe the bug**
as the Title

**To Reproduce**
fill some code which line number is more than 10000.

**Expected behavior**
normal view

**Screenshots/Logs**
![image](https://user-images.githubusercontent.com/22163049/104705973-80392f00-5755-11eb-8002-9a6e12b452d7.png)

**Environment (please complete the following information):**
 - OS: MacBook Pro
 - Browser chrome
 - Bundler webpack

**Comment by domoritz** [comment]
This repo is for the React wrapper for Monaco. Please file issues about Monaco in the Monaco repo.
