### ISSUE TITLE
Identifier 'setImmediate' has already been declared

### ISSUE THREAD

**Issue by C1rdec** [react-monaco-editor/react-monaco-editor#330]
**Describe the bug**
Updating from `0.17.1` to `0.41.2` an exception is thrown.

**To Reproduce**
https://codesandbox.io/s/hopeful-fast-7vhv8?file=/src/App.tsx

**Screenshots/Logs**
![image](https://user-images.githubusercontent.com/5436436/106203731-dc567700-6189-11eb-8f9b-82b94bc957d4.png)

**Comment by frankybboy96** [comment]
Faced the same issue trying to update my version a couple months ago and just dropped the idea. Very interested in knowing how to fix it

**Comment by domoritz** [comment]
Hmm, I just updated all dependencies in 8078676 and the example works fine. Maybe the issue is some other dependencies?

**Comment by C1rdec** [comment]
You have just updated the dependency and you will release a new version?

Because right now any version after `0.26.2` is not working on my side.

**Comment by domoritz** [comment]
Since v0.41.2 there have been no updates out of range so no new release is necessary. Please make sure to run the latest versions. 0.17 is from May 23, 2018 so other dependencies may have changed. 

The linked example has build issues btw. 

<img width="636" alt="Screen Shot 2021-01-28 at 23 34 21" src="https://user-images.githubusercontent.com/589034/106207032-ebcbc500-6175-11eb-866b-bdf673af1219.png">

**Comment by C1rdec** [comment]
>  Please make sure to run the latest versions. 0.17 is from May 23, 2018 so other dependencies may have changed.

That's what I'm trying to do but I'm having this issue.

The provided example works fine on my side you just need to let `code sand box` build the dependency.

![image](https://user-images.githubusercontent.com/5436436/106207889-7ae5d680-6190-11eb-8abb-4d26024a55dd.png)

**Comment by frankybboy96** [comment]
I just tried the sandbox, and it's working fine on my side as well.. Beside the SetImmediate error

**Comment by domoritz** [comment]
Can you repro the issue with the example in this repo?
