### ISSUE TITLE
Uncaught TypeError: Cannot read property 'pushUndoStop' of undefined

### ISSUE THREAD

**Issue by aloneszjl** [react-monaco-editor/react-monaco-editor#332]
https://github.com/react-monaco-editor/react-monaco-editor/blob/462223cbb72301f90541f2424e8c9d954e8c1ce6/src/diff.tsx#L68

The new version of monaco-editor(v0.22.3) cannot find this, modifiedEditor needs to be changed to getModifiedEditor()
![image](https://user-images.githubusercontent.com/19307426/106889559-1fcd5a00-6723-11eb-9973-ee0b281d5022.png)

**Comment by domoritz** [comment]
Can you send a pull request?

**Comment by aloneszjl** [comment]
> Can you send a pull request?

https://github.com/react-monaco-editor/react-monaco-editor/pull/333
