### ISSUE TITLE
close the cursor automatically in the front when I press the Arrowup

### ISSUE THREAD

**Issue by Hidawangdada** [react-monaco-editor/react-monaco-editor#335]
I register a keydown event for the editor like the command line, when I press Arrowup, the value of the editor will be the input that I input before, but the cursor will come to the front, I want to put the cursor at the end. please help me fix the problem

**Comment by domoritz** [comment]
This repo is for the React wrapper for Monaco. Please file issues about Monaco in the Monaco repo. Also, github issues are not for questions.
