### ISSUE TITLE
Cannot set the filename/uri of the editor model

### ISSUE THREAD

**Issue by sgrove** [react-monaco-editor/react-monaco-editor#337]
In order to use Monaco in a few different ways, it's necessary to be able to set the URI of the model that's being edited (e.g. so that the typescript imports are recognized)

The equivalent non-react code would look something like:

```javascript
const model = monaco.editor.createModel(
    `import {add} from 'math';\nconst x = add(3, 5);\n`,
    'typescript',
    monaco.Uri.parse('file:///main.tsx')
);
```

**Describe the solution you'd like**
Just like we can pass in `value`, `defaultValue`, and `options` as props, passing in a `uri` prop that's passed into a newly created model that's passed into the editor creation would make this trivial

**Comment by medihack** [comment]
I want to second this feature. I use a custom language service that can enable/disable features per URI. Would be nice if `react-monaco-editor` would allow to configure the URI of the created model.

**Comment by rahulbanerjee26** [comment]
+1 this would be nice to have

**Comment by amir2mi** [comment]
I come from [#214](https://github.com/remcohaszing/monaco-yaml/issues/214), and I could not find a way to set model URI when creating a new editor, it is a must-have when having multiple editors and the need to set schema validation per editor not for any model.
