### ISSUE TITLE
Can't automatically adapt to browser‘s width

### ISSUE THREAD

**Issue by Biu-Huang** [react-monaco-editor/react-monaco-editor#338]
Using as below:
`
import MonacoEditor from "react-monaco-editor"
<MonacoEditor
          // width='820'
          height='800'
          value = {value}
          language = {"json"}/>
`

when resize the brower's width, react-monaco-editor won't automatically adapt to the new width.
But if i manual refresh the brower, react-monaco-editor will automatically adapt to the new width.

![issue](https://user-images.githubusercontent.com/34543835/109777591-dc410f80-7c3e-11eb-8708-aba19a10b1de.png)

Checked the dom elements, width may be got by calculating, not 100%

**Comment by domoritz** [comment]
Can you try https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.ieditorconstructionoptions.html#automaticlayout ?

**Comment by Biu-Huang** [comment]
> Can you try https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.ieditorconstructionoptions.html#automaticlayout ?

Yes, i have tried adding the attribution of automaticlayout, but the issue still. 
`
import MonacoEditor from "react-monaco-editor" 

<MonacoEditor 
// width='820' 
// automaticLayout
automaticLayout={true}
height='800' 
value={value} 
language={"json"}
/>
`

**Comment by domoritz** [comment]
Then try this approach: https://github.com/vega/editor/blob/0311d5bf6e5fc3eba784cc20ccc14019ff153325/src/components/config-editor/renderer.tsx#L93.

I'm going to close this issue since it looks unrelated to the react bindings. Feel free to continue to ask questions here, though.

**Comment by Biu-Huang** [comment]
Thanks! Refer to the link, i got it.

**Comment by dmytroshch** [comment]
@Biu-Huang you should set automaticlyLayout to options object:
`<Editor
      height='100%'
      width='100%'
      language='javascript'
      theme='vs-dark
      value={value}
      onChange={onChange}
      options={{
        automaticLayout: true,
      }}
    />`
