### ISSUE TITLE
Problems with star version ("*") of monaco-editor dependency

### ISSUE THREAD

**Issue by dkozar** [react-monaco-editor/react-monaco-editor#343]
My project uses both `monaco-editor` and `react-monaco-editor`.

When compiling it, I'm getting:

```bash
Failed to compile.

C:/src/MyProject/src/components/Editor/QueryEditor.tsx
TypeScript error in C:/src/MyProject/src/components/Editor/QueryEditor.tsx(14,106):
Argument of type 'typeof import("C:/src/MyProject/node_modules/react-monaco-editor/node_modules/monaco-editor/esm/vs/editor/editor.api")' is not assignable to parameter of type 'typeof import("C:/src/MyProject/node_modules/monaco-editor/esm/vs/editor/editor.api")'.
  Types of property 'editor' are incompatible.
    Type 'typeof editor' is missing the following properties from type 'typeof editor': onDidChangeMarkers, registerCommand  TS2345

    12 |   const [model, setModel] = useState<monacoEditor.editor.ITextModel | null>(null);
    13 |
  > 14 |   const editorWillMount:EditorWillMount = (monaco): void | EditorConstructionOptions => initializeEditor(monaco, urlTemplates);
       |                                                                                                          ^
    15 |
    16 |   const editorDidMount:EditorDidMount = (editor/*, monaco: typeof monacoEditor*/) => {
    17 |     if (focusOnMount) {
```

In both places `monacoEditor `is referenced as:

`import * as monacoEditor from "monaco-editor/esm/vs/editor/editor.api";`

However, this is what I see in yarn.lock:

```
monaco-editor@*:
  version "0.21.2"
  resolved "https://registry.yarnpkg.com/monaco-editor/-/monaco-editor-0.21.2.tgz#123456"
  integrity sha512-123456==

monaco-editor@0.23.0:
  version "0.23.0"
  resolved "https://registry.yarnpkg.com/monaco-editor/-/monaco-editor-0.23.0.tgz#123456"
  integrity sha512-123456==
```

This is strange since both the _npmjs.com_ and _yarnpkg.com_ show the version `0.23.0` as the latest:

https://www.npmjs.com/package/monaco-editor
https://yarnpkg.com/package/monaco-editor

I'm not fully sure what's going on here, but I assume `react-monaco-editor` is for some rason pulling the older version of the package, which is in conflict with `monaco-editor` version we're using.

Questions:

1. Why the version in your package JSON is marked as star dependency ("*"), which means "latest"?

![image](https://user-images.githubusercontent.com/1078403/112888535-5cd31e80-90cc-11eb-82d2-327f7a8fe7ab.png)
2. Wouldn't it be better to use the fixed version, or peer dependency?
3. Why is the latest version not used, but instead the `0.21.2`?

**Comment by domoritz** [comment]
Try deleting your yarn.lock file and then run yarn again. Does that work?

**Comment by kouknick** [comment]
I too faced an issue today that is related to the `"monaco-editor": "*"` depedency. 

If you check the yarn.lock file in the`react-monaco-editor/example` in line 2896 the editor version is "0.22.2":
```monaco-editor@*:
  version "0.22.2"
  resolved "https://registry.yarnpkg.com/monaco-editor/-/monaco-editor-0.22.2.tgz#ba803bd4adff4f74fe2ea6c20386926444ffdce1"
  integrity sha512-4/PPQiLNRxx3r+FV9Zu/MipM31ZpLNxbg5LKfNU3m82Kp7CCWUSHHTH7JrZ6BasmQgoVjNLQsrqQXb77MSF6lg==
  ```
  If you delete yarn.lock/nodeModules and run `yarn` again in the example project the monaco editor version will be replaced with the new "0.23.0" version which causes a weird error when hovering over suggestions: 

> **errors.js:68 Uncaught (in promise) Canceled: Canceled**

As a workaround in my app I had to include monaco-editor 0.22.2 version in my package.json file and then the *(Any version) resolves to the 0.22.2 version which works fine.

**Comment by dkozar** [comment]
@kouknick, as for the monaco-editor-webpack-plugin, I chacked it previously and it also [uses monaco-editor 0.23.0](https://github.com/microsoft/monaco-editor-webpack-plugin/blob/main/package.json#L38):

![image](https://user-images.githubusercontent.com/1078403/112983828-08748100-9156-11eb-9302-a09903d219ed.png)


https://classic.yarnpkg.com/en/docs/selective-version-resolutions/#toc-how-to-use-it

**Comment by dkozar** [comment]
I found the solution for my problem:

With `yarn`, one is able to "force" the particular version of the dependency, using the [resolutions section in package.json](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/#toc-how-to-use-it):

```json
"resolutions": {
  "monaco-editor": "0.23.0"
},
```

This makes the project and all the dependencies using the same version (0.23.0).

For NPM users, this seems to be slightly more cumbersome: https://www.npmjs.com/package/npm-force-resolutions

**Comment by kouknick** [comment]
@dkozar since you are already using the latest 0.23.0 version don't you experience the aforementioned error when hovering over suggestions? (_**errors.js:68 Uncaught (in promise) Canceled: Canceled**_)

**Comment by dkozar** [comment]
@kouknick I still haven't be able to get any auto-suggestions. My success in solving the issue is related purely to compiling the thing.

My project worked more-or-less properly before the version bump, but now I'm not getting any auto-suggestions.

**Comment by domoritz** [comment]
I just tried the example in the repo and autocomplete still works. I hope you can find out what the issue is.

**Comment by kouknick** [comment]
@domoritz  If I try the example out of the box it works for me too. If I delete yarn.lock file and run yarn again, then I get a console error when mouse out event is triggered on the suggestions. Just tried it again and it is still failing.
