### ISSUE TITLE
Basic intellisense not working - create-react-app

### ISSUE THREAD

**Issue by madatbay** [react-monaco-editor/react-monaco-editor#344]
Hi, I have just simply created react app with `create-react-app`. Then installed (via package manager `npm`) and configured `react-monaco-editor` as shown in docs for simply see how it works. Of course I have configured docs for create-react-app that placed at the end of README.md:
```
1. installed react-app-rewired
2. replaced scripts
3. created config-overrides.js
```
I know that webpack overrides working by logging something. Coloring keywords works too, but intellisense is not working for html, js and etc. that comes with autocomple with monaco editor out of the box

**Comment by domoritz** [comment]
I just tried the example app in this repo and it works fine so I guess the problem must be in create react app. Maybe someone can jump in to help but there is nothing actionable for the code here so I'll close this issue.

**Comment by madatbay** [comment]
I also tried example that works good, but when I try with cra this is not working. Isn't there any extra steps that i should take when working with cra?

**Comment by hedwigz** [comment]
@madatbay try using `yarn` instead of `npm`
