### ISSUE TITLE
在umi3.4.8中使用monaco-editor-webpack-plugin会找不到webpack

### ISSUE THREAD

**Issue by wcxz520** [react-monaco-editor/react-monaco-editor#345]
之前是3.2版本可以用， 升级了umi出现了这个错， 所以初始化了最新版umi项目引入加载依赖就报错。。。

复现: https://github.com/wcxz520/umi-monaco-editor.git

![image](https://user-images.githubusercontent.com/52689177/114330210-ca268b00-9b73-11eb-8eca-a4843aba756f.png)

**Comment by domoritz** [comment]
Please file issues in English.
