### ISSUE TITLE
umi3.4.8 Using the plugin monaco-editor-webpack-plugin will cause an error: Cannot find module 'webpack'

### ISSUE THREAD

**Issue by wcxz520** [react-monaco-editor/react-monaco-editor#346]
https://github.com/wcxz520/umi-monaco-editor.git

yarn

![image](https://user-images.githubusercontent.com/52689177/114330811-1c1be080-9b75-11eb-93e2-0b11220d43fe.png)

**Comment by domoritz** [comment]
Looks like you need to install webpack. I suspect this issue is not in this repo.
