### ISSUE TITLE
Fallback to simple editor (<textarea>?) would be useful for mobile

### ISSUE THREAD

**Issue by filbranden** [react-monaco-editor/react-monaco-editor#350]
monaco-editor is hard to use on a mobile interface. It kind of works, but it's pretty painful to use.

I'd like to request a feature (possibly controlled by user, app using monaco-editor, or automatically based on a media query or similar) to fallback to a very simple editor, such as a <textarea> or perhaps an editable element, while keeping the same API of monaco-editor (IEditor).

Personally, I really like to use websites that use monaco-editor and I often use them on mobile. I don't really mind typing long text on mobile from time to time... But monaco-editor is often fighting me on it... I'd really appreciate having a way to fallback to a "dumber" editor (since I can leave without syntax highlighting, autocompletion, etc. for most use cases where I care about using mobile.)

**NOTE:** Perhaps monaco-editor itself would be a better place to implement this, so I started by filing microsoft/monaco-editor#2480 to request implementing this there, but perhaps implementing it here and offering a consistent React API would be simple, possible, useful... So filing it here too. Feel free to close and/or comment there if you think that layer is more appropriate.

(NOTE: I'm not really knowledgeable in most of the technologies involved here, such as ES, React, etc. I'm filing this from an user's point of view. So forgive if I got some of the details incorrectly.)

**Comment by domoritz** [comment]
I think this makes sense as a suggestion but I think it's best done in Monaco. Thanks for filing the issue there already.
