### ISSUE TITLE
TypeError: Cannot read property 'run' of null

### ISSUE THREAD

**Issue by hyy520** [react-monaco-editor/react-monaco-editor#353]
editor.getAction('editor.action.formatDocument') 返回null ，无法执行run()

代码：
class EditorField extends PureComponent {
	constructor(props) {
		super(props);
	}

	async editorDidMountHandle(editor) {
		setTimeout(() => {
			editor.getAction('editor.action.formatDocument').run();
		}, 500);
	}

	render() {
		const editorOptions = {
			selectOnLineNumbers: true,
			readOnly: !this.props['editType'],
		};

		return (
			<FormItem name={this.props['dkey']} {...this.props['fieldOptions']}>
				<MonacoEditor
					height="300"
					language="json"
					theme="vs-dark"
					value={this.props['value']}
					options={Object.assign(editorOptions, this.props['fieldProps'])}
					onChange={this.props['onChange']}
					editorDidMount={this.editorDidMountHandle}
				/>
			</FormItem>
		);
	}
}

**Comment by domoritz** [comment]
Unclear issue. Please file an issue with a clear description and minimal example.
