### ISSUE TITLE
build breaks with latest version of monaco-editor and webpack-plugin

### ISSUE THREAD

**Issue by Nishchit14** [react-monaco-editor/react-monaco-editor#392]
**Describe the bug**
The latest version of the `react-monaco-editor@0.44.0` is breaking while bundling with webpack v4.
```
"monaco-editor-webpack-plugin": "^4.0.0"
"monaco-editor": "^0.27.0"
```

**To Reproduce**
follow this thread and comments https://github.com/microsoft/monaco-editor-webpack-plugin/issues/152#issuecomment-903718602

**Expected behavior**
It should work with the latest version of monaco-editor and monaco-editor-webpack-plugin.

**Environment (please complete the following information):**
 - OS: Mac
 - Browser: Chrome
 - Bundler : webpack

**Comment by domoritz** [comment]
Can you send a pull request to update the deps and show the error in the example in this repo?
