### ISSUE TITLE
Can't resolve 'monaco-editor/esm/vs/editor/editor.api' (when using different Monaco versions in the same project)

### ISSUE THREAD

**Issue by dkozar** [react-monaco-editor/react-monaco-editor#403]
**Describe the bug**

We've build a library which uses `react-monaco-editor` as dependency.

In its `package.json`, we've specified the version of `monaco-editor` we want to use:

```
"dependencies": {
    "monaco-editor": "^0.27.0",
},
"resolutions": {
    "monaco-editor": "^0.27.0",
},
```

The user would like to use the library in a project which uses an older version of `monaco-editor` (0.10.x). Changing the Monaco version used by this project is currently not possible.

When running the build, we're getting:

`Module not found: Error: Can't resolve 'monaco-editor/esm/vs/editor/editor.api' in 'C:\src\TheProject\node_modules\react-monaco-editor\lib'`

**Expected behavior**

It looks `react-monaco-editor` targets `monaco-editor` sitting  directly in project's `node_modules`. This older version doesn't have the `/esm/vs/editor/editor.api` path.

We'd expect `react-monaco-editor` targeting it's own version of `monaco-editor` (which lives in `react-monaco-editor/node_modules/monaco-editor`), and not the one in `node_modules` of the project.

Only in case when both versions are the same, we'd expect it to use the one in project's _node_modules_ (standard NPM practice).

**Screenshots/Logs**

This is the line referencing the non-existing `editor.api` and causing the issue:

![image](https://user-images.githubusercontent.com/1078403/132030029-428956e3-f4e3-418f-b3b9-913c78f24a7c.png)

**Environment (please complete the following information):**
 - OS: Windows
 - Bundler: Webpack

**Comment by domoritz** [comment]
> We'd expect react-monaco-editor targeting it's own version of monaco-editor (which lives in react-monaco-editor/node_modules/monaco-editor), and not the one in node_modules of the project.

Usually, dependencies get hoisted to the top level unless there is a version conflict. If you want to use a newer version of monaco, please send a pull request to update the version in this repo.

**Comment by dkozar** [comment]
The version conflict is welcome it my case, as I'd like to have 2 different instances of Monaco in the dingle page app (different versions will never be on screen at the same time).

Could you please reopen?

**Comment by dkozar** [comment]
To illustrate what's expected: 

```
project
   |
   --- node_modules
                  |
                  --- monaco-editor (0.10.x)
                  --- react-monaco-editor
                                     |
                                     --- node_modules
                                                    |
                                                    --- monaco-editor (0.27.0)
```

**Comment by domoritz** [comment]
I see. That seems like an issue with monaco or the webpack monaco plugin or webpack rather than this package, though. If you disagree, I can reopen.

**Comment by colombod** [comment]
I am having same issues despite the fact that I have same version of monaco as the react-monaco-editor. If I remove the monaco-editor pacakge then the monaco-editor-webpack-plugin has issues

**Comment by dkozar** [comment]
I managed to fix the issue using **package alias**:

- https://npm.community/t/release-npm-6-9-0/5911
- https://dev.to/abdelrahmanahmed/package-alias-name-using-npm-yarn-d9p

Important: NPM understands aliases from version _6.9.0 onwards_.

I renamed the older version of Monaco, so at the end both versions sit in "top level" `node_modules` folder (the one belonging to the app). Only with this change, the paths work.

![image](https://user-images.githubusercontent.com/1078403/134326144-82539b8e-9cf5-4f45-8d9d-e679d67d6866.png)

![image](https://user-images.githubusercontent.com/1078403/134326383-1b5f3078-379e-4478-9a79-ea5f17a7b5d7.png)

I would also say that **getting messages related to paths is an indication one's dealing with different versions of Monaco editor within the same project**.

Not only `react-monaco-editor` references some resources in a wrong path, but also `monaco-editor` itself changed paths in newer versions (for instance this is one of the changes: https://github.com/microsoft/monaco-editor/commit/1ba6bff6f70e03f3ed9c90a6aab0b3e525589849).

This causes errors such as:

```
./node_modules/monaco-editor/esm/vs/base/browser/ui/codicons/codicon/codicon.ttf 1:0
Module parse failed: Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
```
