### ISSUE TITLE
Publish new version of library for monaco-editor 0.27 (code changed made, just needs publish)

### ISSUE THREAD

**Issue by patrickshipe** [react-monaco-editor/react-monaco-editor#405]
**Describe the bug**
When using with monaco-editor 0.27, there are typing conflicts. If we publish a version of this library using the current code base this will fix the problem.

**To Reproduce**
Install the latest published version alongside editor version 0.27. Types will not be compatible.

**Expected behavior**
Types are compatible.

**Screenshots/Logs**
```
Type 'import("node_modules/react-monaco-editor/node_modules/monaco-editor/esm/vs/editor/editor.api").editor.IStandaloneDiffEditor' is not assignable to type 'import("node_modules/monaco-editor/esm/vs/editor/editor.api").editor.IStandaloneDiffEditor'.
  Types of property 'addAction' are incompatible.
```

**Environment (please complete the following information):**
 - OS: [e.g. Linux]
 - Browser [e.g. Firefox, Safari]
 - Bundler [e.g. webpack]

- [ ] I will try to send a pull request to fix this issue.

**Comment by domoritz** [comment]
0.45 will be out soon
