### ISSUE TITLE
Manually execute "Format Code" action

### ISSUE THREAD

**Issue by dhwaj1902** [react-monaco-editor/react-monaco-editor#411]
Is it possible to manually execute the "Format Code" action using a button in ``react-manco-editor``?
Thanks!

**Comment by domoritz** [comment]
I think you can call actions on the editor instance. Look at the Monaco api.

**Comment by 1195002442** [comment]
> 

editorDidMount = (editor, monaco) => {
    console.log('editorDidMount', editor)
    setTimeout(() => {
      editor.getAction('editor.action.formatDocument').run()
    }, 300)
    editor.focus()
  }


<MonacoEditor
            width="100%"
            height={document.body.clientHeight - 200}
            theme="vs-dark"
            language={'json'}
            options={{ automaticLayout: true, minimap: { enabled: false }}}
            onChange={(value, event) => { }}
            value={newValue}
            editorDidMount={this.editorDidMount}
          />
