### ISSUE TITLE
Text is always black or white

### ISSUE THREAD

**Issue by KentonParton** [react-monaco-editor/react-monaco-editor#466]
**Describe the bug**
The text in the editor is always white for theme vs-dark and black for vs-light.

**To Reproduce**
Create new react app with "npx create-react-app my-app". Install react-monaco-editor, use code from readme. Set theme to vs-light or vs-dark 

**Expected behavior**
I would expect token highlighting to use the defaults from the two themes and be overridable via monaco.editor.defineTheme.

**Screenshots/Logs**
<img width="962" alt="Screen Shot 2021-12-23 at 9 07 57 PM" src="https://user-images.githubusercontent.com/20202312/147291559-d8671292-0e57-4ebd-b345-37dfc600090d.png">

<img width="955" alt="Screen Shot 2021-12-23 at 9 07 35 PM" src="https://user-images.githubusercontent.com/20202312/147291563-181308a6-4a38-46be-942f-164dc68f4484.png">

**Environment (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Bundler None

**Comment by domoritz** [comment]
Try the example in the example folder. I suspect your editor has an error where the formatters don't get loaded. Make sure you have the correct webpack setup.
