### ISSUE TITLE
how can i fold the same lines when i use DiffEditor

### ISSUE THREAD

**Issue by LeePiaPia** [react-monaco-editor/react-monaco-editor#502]
this is what i want, how can i set the options?
![image](https://user-images.githubusercontent.com/23470187/155646772-ef53c59d-3316-49c4-8f60-9cbbd0babc4c.png)

**Comment by domoritz** [comment]
This repo is for the React wrapper for Monaco. Please file issues about Monaco in the Monaco repo.
