### ISSUE TITLE
`KeyCode` alphabetical values are `undefined`

### ISSUE THREAD

**Issue by louis-cf-lin** [react-monaco-editor/react-monaco-editor#503]
**Describe the bug**
I'm trying to add a new `Ctrl + S` keybinding by using the `addAction` method. The code looks like this

```js
editor.addAction({
  id: "save",
  label: "Save",
  keybindings: [monaco.KeyMod.CtrlCmd | monaco.KeyCode.KeyS],
  contextMenuGroupId: "2_basic",
  run: function (ed) {
  alert("i'm running => " + ed.getPosition());
  },
});
```

This doesn't seem to be working, and the value of `monaco.KeyCode.KeyS` seems to return `undefined`. I've tested various keycode values and this seem to only happen to the alphabetical keys, e.g. `KeyA`, `KeyB`, ... , `KeyZ`. I think there's an error in the enum definition, but I'm not entirely certain. What does work is changing the keybinding to

```js
  keybindings: [monaco.KeyMod.CtrlCmd | monaco.KeyCode.KEY_S],
```

which actually raises a linting error. In general, I believe the enum value for alphabetical keys needs to be updated.

This issue doesn't exist in Monaco itself as using `monaco.KeyCode.KeyS` works fine.

**To Reproduce**
A Monaco editor in a NextJS project with the above code chunk.

**Expected behavior**

`KeyCode.KeyS` should be a valid number, not `undefined`.

**Screenshots/Logs**

![image](https://user-images.githubusercontent.com/46121192/155888780-ea121040-982e-4fe5-891a-2072b70ecc81.png)

![image](https://user-images.githubusercontent.com/46121192/155888789-70c651c9-b43f-47f2-be60-1a1838876c5e.png)

**Environment (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Bundler: Webpack

- [ ] I will try to send a pull request to fix this issue.

**Comment by domoritz** [comment]
This repo is for the React wrapper for Monaco. Please file issues about Monaco in the Monaco repo.
