### ISSUE TITLE
Handle paste event to customize effect

### ISSUE THREAD

**Issue by NicoLaval** [react-monaco-editor/react-monaco-editor#519]
We didn't find a way to handle `paste` event, I mean different from an input event.

Depending on the source, special characters appear sometimes when pasting, and we would be able to clean them (and f it is therefore possible to capture this particular event, it would be less expensive than applying then to each onChange triggered)

**Comment by domoritz** [comment]
This repo is for the React wrapper for Monaco. Please file issues about Monaco in the Monaco repo.
