### ISSUE TITLE
Animation not loading in mobile browsers

### ISSUE THREAD

**Issue by awsdyn** [react-monaco-editor/react-monaco-editor#520]
**Describe the bug**
I have followed the documentation and implemented everything in my Next.js project. Animation is working perfectly in Desktop browsers but animation remains blank in mobile browsers. I have tested it in both Android and iOS. Can anyone help me out?

**To Reproduce**
Download the  "developer.lootie" file from here - [https://www107.zippyshare.com/v/kbeBPeaz/file.html](https://www107.zippyshare.com/v/kbeBPeaz/file.html) and place it in your project "public/developer.lottie". or you can try and .lottie file. Then create a ".env.local" file and place the below line there -

`
NEXT_PUBLIC_URL=http://localhost:3000
`

Just create a blank Next.js project and place the below code in pages/index.js file. 
```jsx
import { useEffect } from "react";

export default function Home() {
  useEffect(() => {
    import("@dotlottie/player-component");
  });

  return (
      <div className="min-h-[calc(100vh_-_81px)] ">
        <div className="max-w-lg">
          <dotlottie-player src={`${process.env.NEXT_PUBLIC_URL}/developer.lottie`} autoplay loop style={{ height: "100%", width: "100%" }} />
        </div>
      </div>
  );
}

```

**Expected behavior**
If you run "npm run dev" in your terminal and open the browser and visit http://localhost:3000, the animation should load properly. Everything is working absolutely fine in all desktop browsers. But when I check it from mobile browsers, the animation remains blank. Please check the below screenshots.

**Screenshots/Logs**

Desktop Browser:

<img width="1426" alt="desktop" src="https://user-images.githubusercontent.com/101019220/159660452-87b70d1c-fd0f-4728-ad29-c4a983c13f11.png">

iPhone Safari

![iphone](https://user-images.githubusercontent.com/101019220/159660527-7c34107d-7422-47fd-8fb6-5320f833cbb1.jpeg)

**Environment (tested in iPhone and Macbook pro):**
 - OS: [Mac, Window, Lunux]
 - Browser [Firefox, Safari, Chrome and Edge]
 - Bundler [webpack]
 - Framework [Next.js]
 - Library [React.js]

**Comment by domoritz** [comment]
This repo is for the React wrapper for Monaco. Please file issues about Monaco in the Monaco repo.
