### ISSUE TITLE
About the release of react-monaco-editor v0.48.0

### ISSUE THREAD

**Issue by PisecesPeng** [react-monaco-editor/react-monaco-editor#541]
👋 Hi~
I recently encountered some special whitespace display problems in the editor
> The display of NBSP is supported in the new version of monaco editor
<img width="354" alt="image" src="https://user-images.githubusercontent.com/29013341/164873164-03576481-9922-48a6-9912-91da29eb1ef9.png">

> In fact, I noticed that there was already an update in the commit
<img width="536" alt="image" src="https://user-images.githubusercontent.com/29013341/164873201-8ec99e0b-64ab-4dae-8093-351d3b71e91c.png">

😂 so... is there any plan to release version 0.48.0?

Look forward to your reply!

**Comment by domoritz** [comment]
0.48.0 is out
