### ISSUE TITLE
Module parse failed: Unexpected token (33:15)

### ISSUE THREAD

**Issue by huilingaa** [react-monaco-editor/react-monaco-editor#577]
npm run start：
Module parse failed: Unexpected token (33:15)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
| 
| var LanguageServiceDefaultsImpl = class {
>   _onDidChange = new monaco_editor_core_exports.Emitter();
|   _diagnosticsOptions;
|   _modeConfiguration;

**Comment by domoritz** [comment]
I don't think there is enough detail here to debug or see an issue with this library.
