### ISSUE TITLE
completion using registerCompletionItemProvider fail

### ISSUE THREAD

**Issue by jfroffice** [react-monaco-editor/react-monaco-editor#613]
**Describe the bug**

I noticed that partial monaco import causes completion to fail.

the replacement of
```
import * as monaco from "monaco-editor/esm/vs/editor/editor.api";
```

to 

```
import * as monaco from "monaco-editor";
```

make the completion to work.

**Comment by domoritz** [comment]
I think that makes the bundle bigger, no?

**Comment by jfroffice** [comment]
Yes definitely.

For info, I have found that by adding
```
import 'monaco-editor/esm/vs/editor/contrib/suggest/browser/suggestController.js';
```

it add partial completion of local words already present in the current file.


But I am still not able to add the completion programmatically using `monaco.languages.registerCompletionItemProvider`

**Comment by domoritz** [comment]
I think we had this issue before and the solution was to use https://github.com/Microsoft/monaco-editor-webpack-plugin. If you can reproduce the issue with the examples in this repo, we can reopen the issue.

**Comment by jfroffice** [comment]
Thank you @domoritz, but I am working on the `vite` bundler. And I did find any work-around for now.
