### ISSUE TITLE
Update to `monaco-editor` `^0.34`

### ISSUE THREAD

**Issue by wudstrand** [react-monaco-editor/react-monaco-editor#617]
**Is your feature request related to a problem? Please describe.**
In order for this component to work with the `monaco-languageclient` `monaco-editor` needs to be updated to `v0.34`

**Describe the solution you'd like**
Update the version of `monaco-editor` from `^0.33` to `^0.34`

**Comment by wudstrand** [comment]
@domoritz When will this update be released to npm?

**Comment by domoritz** [comment]
0.50 is out
