### ISSUE TITLE
AddAction with function that changes

### ISSUE THREAD

**Issue by nfiacco** [react-monaco-editor/react-monaco-editor#628]
**Describe the bug**
I want to add an action to the Monaco editor, but because the function changes (it uses a React state value that changes), this doesn't work. Since the AddAction has to happen in the editorDidMount function, I think it only gets added once.

**Expected behavior**
The action changes whenever the function passed to it changes.

**Comment by domoritz** [comment]
Can you add a function as a closure that calls a function stored in a variable?

**Comment by nfiacco** [comment]
Is this what you're suggesting:
```
const [x, setX] = useState("test");
const doAction = () => console.log(x);

<MonacoEditor
  editorDidMount={(editor: EditorLib.IStandaloneCodeEditor) => {
    editor.addAction({ id: "action", label: "action", keybindings: [monaco.KeyMod.CtrlCmd | monaco.KeyCode.Enter], run: () => doAction, });
  }}
/>
```

I had tried something similar, but still no luck

**Comment by domoritz** [comment]
It should be doAction() in the call

**Comment by domoritz** [comment]
I'm closing this since this is not an issue with the react library.
