### ISSUE TITLE
Could not parse entire input

### ISSUE THREAD

**Issue by mylesshie** [react-monaco-editor/react-monaco-editor#668]
**Describe the bug**
`
./node_modules/monaco-editor/esm/vs/base/browser/dom.js
SyntaxError: /Users/mike/Documents/work/saas-b2b/node_modules/monaco-editor/esm/vs/base/browser/dom.js: Could not parse entire input - got stuck at position 87
    ?:[\w\_])+))?
`
**Environment (please complete the following information):**
react: 16
webpack: 4

when I run my App, I got this error.

**Comment by domoritz** [comment]
Thanks for the report. Can you provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates the issue? This looks like an error with your setup.
