### ISSUE TITLE
auto layout size is not available

### ISSUE THREAD

**Issue by HRan2004** [react-monaco-editor/react-monaco-editor#669]
<MonacoEditor
    language="javascript"
    theme="vs"
    value={code}
    options={options}
    onChange={onChange}
    editorDidMount={editorDidMount}
    automaticLayout={true}
  />

I use 'automaticLayout', but when the parent element size change, the content in the monaco editor are not fresh.

**Comment by domoritz** [comment]
Thanks for the report. Can you provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that demonstrates the issue?
