### ISSUE TITLE
Respect user's preferred color scheme

### ISSUE THREAD

**Issue by Sboonny** [react-monaco-editor/react-monaco-editor#688]
**Is your feature request related to a problem? Please describe.**
Yes, in freeCodeCamp https://github.com/freeCodeCamp/freeCodeCamp/issues/48936, we changed our theme through [`preferred-color-scheme`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme), but didn't set value for `theme`, which lead the site having dark mode colors without theme.

This led to two different state for the site and the editor, the site being `night-mode` and the editor `vs-light`

*Screenshots*

<img width="1400" alt="Screen Shot 2023-01-03 at 3 12 59 PM" src="https://user-images.githubusercontent.com/4591597/210774718-a54c08cc-1915-4379-aa5e-8fe554f1a8ff.png">

**Describe the solution you'd like**

We can use some logic to set the theme, if the user prefers dark color scheme.

```ts
const preferDarkScheme = window.matchMedia(
    '(prefers-color-scheme: dark)'
  ).matches;
```

We can use the code above to set the logic in section below

https://github.com/react-monaco-editor/react-monaco-editor/blob/66b4f07f6ee7498fa8cdcf55cfaa2a4e409f3c65/example/index.js#L42-L79

To have something like this: 

```ts
 render() { 
   const { code, theme } = this.state
   const preferDarkScheme = window.matchMedia(
    '(prefers-color-scheme: dark)'
  ).matches;
  const preferredUserTheme = preferDarkScheme ? "vs-dark" : "vs-light";
  
  return( 
  ...
  <MonacoEditor
          height="400"
          language="javascript"
          value={code}
          options={options}
          onChange={this.onChange}
          editorDidMount={this.editorDidMount}
          theme={theme || preferredUserTheme}
        />
        
 ```
 
 This should set theme, if the `theme` value is empty

**Comment by domoritz** [comment]
Isn't this an issue with Monaco itself rather than the text wrapper?

**Comment by Sboonny** [comment]
Yeab, you are right.

It has the CSS files in it https://github.com/microsoft/monaco-editor/blob/main/website/monarch/monarch.css, so there is possibility of adding a simpler solution, as well.

I am moving this issue there 👍, thank you for the quick response.
