### ISSUE TITLE
Version 0.51.0 appears to introduce flicker in syntax highlighting during rapid text entry

### ISSUE THREAD

**Issue by shepmaster** [react-monaco-editor/react-monaco-editor#689]
# Describe the bug

Version 0.51.0 appears to introduce flicker in syntax highlighting during rapid text entry:

**react-monaco-editor@0.50.1**

![2023-01-20 12 59 39](https://user-images.githubusercontent.com/174509/213773821-03b2709b-6454-4706-853b-50444b6ddd23.gif)

**react-monaco-editor@0.51.0**

![2023-01-20 13 02 26](https://user-images.githubusercontent.com/174509/213773797-b04bdf10-a835-4893-8556-bd3369aaf5c0.gif)

I did not change my version of Monaco between those two tests.

The [original report](https://github.com/integer32llc/rust-playground/issues/885) has an additional GIF.

# To Reproduce

I am still working on succinct reproduction steps, but wanted to open the issue early to link to it.

# Expected behavior

There would not be any flicker.

# Environment (please complete the following information)

 - I've seen this in Chrome `Version 111.0.5506.0 (Official Build) canary (arm64)` on macOS. The people reporting it to me say they've verified on both Windows and macOS, both Chrome and Firefox. 
 - webpack@5.24.3
 - monaco-editor-webpack-plugin@7.0.1
 - monaco-editor@0.34.1

- [x] I will try to send a pull request to fix this issue if I can identify it and I have time.

**Comment by d3x42** [comment]
Same issue for me. Still can't get how to reproduce it

**Comment by shepmaster** [comment]
If you apply this patch to the example provided in the repository:

```diff
diff --git a/example/index.js b/example/index.js
index ccb3616..932b4d2 100644
--- a/example/index.js
+++ b/example/index.js
@@ -12,7 +12,7 @@ class CodeEditor extends React.Component {
   }
 
   onChange = (newValue) => {
-    console.log("onChange", newValue); // eslint-disable-line no-console
+    this.setState({ code: newValue });
   };
 
   editorDidMount = (editor) => {
```

You'll see the flickering behavior:

![2023-01-24 11 59 02](https://user-images.githubusercontent.com/174509/214358153-6dbd5071-a8e9-451b-afb1-69da4a51fec5.gif)

I often get "controlled" and "uncontrolled" mixed up, but it seems strange that your controlled example doesn't update the state in response to editor change events. Without that, it seems like React (or Redux in my case) isn't really the true owner of the state. You'd be required to reach in and grab the current value out of the editor.

I had [similar problems when adapting the Ace editor](https://github.com/integer32llc/rust-playground/blob/578f5d2c599e93e9fb4ab7edf0ab7c241d5960c7/ui/frontend/editor/AceEditor.tsx#L170-L198). There, the problem was that data flowed out of the change event, back to the state, then back to the `value` prop. That causes the editor to dump the content and restart, which should explain the flash. For Ace, I added extra checks to prevent that unneeded work, the primary one being a check to see if the editor's text differed from the prop's text.
