### ISSUE TITLE
Using with browserify

### ISSUE THREAD

**Issue by lambert-velir** [react-monaco-editor/react-monaco-editor#73]
Hi!

I'm having a very hard time using this with Browserify.  The problem is here: https://github.com/superRaytin/react-monaco-editor/blob/master/src/editor.js#L130-L150

Browserify defines `window.require`, so this `if` statement is assuming that the AMD loader is `window.require`.  It then tries to load monaco through browserify (https://github.com/superRaytin/react-monaco-editor/blob/master/src/editor.js#L109-L112)
which doesn't work...

Any ideas?

**Comment by benatkin** [comment]
I was having trouble getting it to work with Next.js which defines some globals on window, and it started working well as soon as I switched to [an alternative distribution of monaco-editor](https://github.com/timkendrick/monaco-editor). https://github.com/resources/snippets/tree/master/monaco-editor-with-next

**Comment by domoritz** [comment]
I think this will be possible with the next version of monaco.
