### ISSUE TITLE
Get last token from document object

### ISSUE THREAD

**Issue by JJ810** [react-monaco-editor/react-monaco-editor#732]
## Description

We are trying to implement our custom language editor but I wanted to ask if there is a method which we can use to get the last token.

i.e:
if expression input is `email.substring(1, 2)`
We want to have `getLastToken()` method which returns `substring(1, 2)`
```ts
document.getLastToken() //  returns substring(1, 2)
```

We are currently using our own helper function by splitting inputs with space
```ts
export const getCurrentTextToken = (
  document: monaco.editor.ITextModel,
  position: monaco.Position
): string => {
  const { lineNumber, column } = position;
  const currentText = document
    .getLineContent(lineNumber)
    .slice(0, column - 2);
  const tokens = currentText.split(" ");
  return tokens[tokens.length - 1];
};
```

The reason why we are NOT splitting it by `.` is because we also have namespaces(i.e: `user.data.email`) and we should get the entire object in order to get the return type and show corresponding suggestions.

Please let me know if there is a way to make this work. Thanks in advance!

**Comment by domoritz** [comment]
This repo is for the React wrapper for Monaco. Please file issues about Monaco in the Monaco repo.
