### ISSUE TITLE
Set cursor position after insert

### ISSUE THREAD

**Issue by JJ810** [react-monaco-editor/react-monaco-editor#733]
## Description

So after suggestion text insert we want to control the cursor position.

i.e:  In this screen recording I want to move cursor inside `()` but I couldn't find a way to do it?

https://user-images.githubusercontent.com/59910709/232865181-57e65668-c4e5-43b4-b43e-5c9c8cc50126.mov

Is there a possible way to do this? Thanks in advance!

**Comment by domoritz** [comment]
This repo is for the React wrapper for Monaco. Please file issues about Monaco in the Monaco repo.
