### ISSUE TITLE
ModelMarkers doesn't work. It didn't show error any more

### ISSUE THREAD

**Issue by limingu** [react-monaco-editor/react-monaco-editor#735]
**Describe the bug**
We use react-monaco-editor version 0.52.0. The error message didn't show any more. If we revert back to react-monaco-editor version 0.46.0, then it works fine.

No error message showing (version 0.52.0)
![image](https://user-images.githubusercontent.com/48228819/234152513-c05ebdea-3f81-4dc3-bdb9-427a023df78a.png)

**Expected behavior**

Showing error message (version 046.0)
![image](https://user-images.githubusercontent.com/48228819/234152703-9a7feb87-e2ae-4093-8ecc-9fcf17522f8a.png)

**Screenshots/Logs**
If applicable, add screenshots or logs to help explain your problem.

**Environment (please complete the following information):**
 - OS: [e.g. Linux]
 - Browser [e.g. Firefox, Safari]
 - Bundler [e.g. webpack]

- [ ] I will try to send a pull request to fix this issue.

**Comment by imsiddhartha** [comment]
I am facing the same issues in v0.52.0
