### ISSUE TITLE
0.54.0版本引入报错

### ISSUE THREAD

**Issue by tushuang** [react-monaco-editor/react-monaco-editor#803]
**Describe the bug**
更新到最新版本0.54.0后报错，错误信息：
Uncaught TypeError: process.getuid is not a function

**To Reproduce**
A clear description of the environment that causes this bug. Please test the example in the `example` folder.

**Expected behavior**

**Screenshots/Logs**
If applicable, add screenshots or logs to help explain your problem.

**Environment (please complete the following information):**
 - OS: [e.g. Linux]
 - Browser [e.g. Firefox, Safari]
 - Bundler [e.g. webpack]

- [ ] I will try to send a pull request to fix this issue.

**Comment by domoritz** [comment]
Please file issues in English
