### ISSUE TITLE
Broken on v0.41.0 of monaco-editor

### ISSUE THREAD

**Issue by eraffel-MDSol** [react-monaco-editor/react-monaco-editor#808]
Not sure if this is something specific to my setup, or a bug in Monaco, or a breaking change, but using C#, a lot of features stop working going from 0.40.0 to 0.41.0, for example auto-bracket-matching.

**Comment by domoritz** [comment]
Unfortunately, this isn't an actionable issue. Can you make an issue for a specific thing that doesn't work anymore and identify what change has caused this breakage?

**Comment by eraffel-MDSol** [comment]
I just pinned to v0.40.0
