### ISSUE TITLE
Expose 'model' prop

### ISSUE THREAD

**Issue by TedDriggs** [react-monaco-editor/react-monaco-editor#94]
[`monaco.editor.IEditorConstructionOptions`](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.ieditorconstructionoptions.html) exposes a `model` property, with subsequent updates to the property happening through the [`ICodeEditor.setModel`](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.editor.icodeeditor.html#setmodel) method.

This dichotomy prevents the property from being exposed via the `options` object, but it could be exposed as a direct prop, with changes handled in `componentWillReceiveProps`.

I'd be happy to submit a PR for this.

**Comment by domoritz** [comment]
That would be great. Also, I'd love to see an example of how this is used.

**Comment by domoritz** [comment]
You can access the model via the editor in `editorDidMount`.

**Comment by TedDriggs** [comment]
I think the request here was to support _setting_ the `model` via a prop, rather than reading it.

**Comment by domoritz** [comment]
You can access the editor and set the model that way but I suspect that this might cause some inconsistencies. It would be nice to have a model react property to set the model. Happy to review a PR.
