### ISSUE TITLE
Inconsistent versioning. Published NPM Package is outdated

### ISSUE THREAD

**Issue by angelsvirkov** [react-monaco-editor/react-monaco-editor#954]
**Describe the bug**
The published npm version of this package is outdated and contains `monaco-editor: "^0.44.0"` in the peer dependency at the time of writing this issue on 05.08.2024, whereas the repo contains monaco-editor version `^0.50.0` already. 

**To Reproduce**
See current code https://github.com/react-monaco-editor/react-monaco-editor/blob/master/package.json and published code at https://www.npmjs.com/package/react-monaco-editor?activeTab=code 

**Expected behavior**
Every time the peer dependency is updated, react-monaco-editor needs to bump its version (probably a patch) and re-publish to NPM because otherwise the consumers of `react-monaco-editor` get outdated peer dependency requirement in their dependency managers.

**Comment by domoritz** [comment]
Yeah, I don't actively maintain this package anymore so updates will be sporadic but I can make releases when needed. I just pushed a new version from master: 0.56.0. Thanks for the ping.
