### ISSUE TITLE
Spawning two editors on a page results in both onChange handlers binding to the second editor

### ISSUE THREAD

**Issue by captbaritone** [react-monaco-editor/react-monaco-editor#964]
**Describe the bug**
If I mount two editors on the same page, and add an `onChange` handler to both, the handler of the second component gets called for changes in both editors.

I downgraded to `0.55.0` and that seems to have fixed the issue.

**Comment by bysking** [comment]
+1

**Comment by broox** [comment]
i have also run into this. `0.56.0` works just fine, `0.56.1` introduces the issue.

i believe that [this is the culprit](https://github.com/react-monaco-editor/react-monaco-editor/pull/955)

**Comment by debugmiller** [comment]
This seems to have been introduced between `0.56.0` and `0.56.1`. The only commit was https://github.com/react-monaco-editor/react-monaco-editor/commit/218893e15737b8863e61bb12b00cf6186bc80b27

**Comment by domoritz** [comment]
@Elessar1802 can you fix this or send a pull request to revert this?

**Comment by Elessar1802** [comment]
@domoritz Sure will send a fix for this

**Comment by Elessar1802** [comment]
@domoritz created a [PR](https://github.com/react-monaco-editor/react-monaco-editor/pull/976) to fix this issue.
